"""Build NCE2's offline pack from the checked-in vocabulary and authored examples.

Optional --source-html imports a local snapshot of the user-specified public word
list. Never downloads lesson prose, audio, or user data. Runtime has no network.
"""
from pathlib import Path
import argparse
import csv
import html
import json
import re

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content/nce2"


def clean(value):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", value))).strip()


def import_source(path):
    tokens = re.finditer(r'(?s)<h3\s+class="h4 my-3 text-center text-md-start">(.*?)</h3>|'
                         r'<div\s+class="col-12 col-md-6 col-lg-4 border-bottom pt-1 mb-1">(.*?)</div>',
                         path.read_text(encoding="utf-8"))
    entries, lessons, words = 0, set(), {}
    for token in tokens:
        if token[1] is not None:
            lesson = int(re.search(r"Lesson\s+(\d+)", clean(token[1]))[1])
            lessons.add(lesson)
            continue
        block = token[2]
        match = re.search(r'data-word="([^"]+)"', block)
        if not match:
            continue
        entries += 1
        word = html.unescape(match[1]).strip()
        fields = re.findall(r'(?s)<small\s+class="text-gray">(.*?)</small>', block)
        pos = re.search(r'(?s)<span\s+class="badge[^"]*">(.*?)</span>', block)
        phonetic = re.sub(r"^/\s*|\s*/$", "/", clean(fields[0]))
        meaning = (clean(pos[1]) + " " + clean(fields[-1])).strip()
        item = words.setdefault(word.lower(), [word, phonetic, [], []])
        if meaning not in item[2]:
            item[2].append(meaning)
        if lesson not in item[3]:
            item[3].append(lesson)
    assert (entries, len(words), lessons) == (877, 851, set(range(1, 97)))
    CONTENT.mkdir(parents=True, exist_ok=True)
    with (CONTENT / "vocabulary.tsv").open("w", encoding="utf-8", newline="") as target:
        writer = csv.writer(target, delimiter="\t", lineterminator="\n")
        for word, phonetic, meanings, numbers in words.values():
            writer.writerow([word, phonetic, "；".join(meanings), ", ".join(f"NCE2 Lesson {n}" for n in numbers)])


def build():
    def rows(name):
        with (CONTENT / name).open(encoding="utf-8") as stream:
            return list(csv.reader(stream, delimiter="\t"))
    vocabulary = rows("vocabulary.tsv")
    examples = rows("examples.tsv")
    assert len(vocabulary) == 851 and all(len(row) == 4 for row in vocabulary)
    assert all(len(row) == 3 for row in examples)
    by_word = {row[0].lower(): row[1:] for row in examples}
    corrections = {key.lower(): value for key, value in json.loads((CONTENT / "corrections.json").read_text(encoding="utf-8")).items()}
    assert len(by_word) == len(examples) == 851
    assert set(by_word) == {row[0].lower() for row in vocabulary}
    assert set(corrections) <= set(by_word)
    output = []
    for word, phonetic, meaning, lesson in vocabulary:
        sentence, translation = by_word[word.lower()]
        correction = corrections.get(word.lower(), {})
        phonetic = correction.get("phonetic", phonetic)
        meaning = correction.get("meaning", meaning)
        word = correction.get("word", word)
        assert all([word, meaning, lesson, sentence, translation]), word
        assert phonetic or "音标待核对" in meaning, word
        assert re.search(r"(?<![A-Za-z])" + re.escape(word) + r"(?![A-Za-z])", sentence, re.I), word
        assert len(sentence.split()) <= 18, (word, sentence)
        assert not any('$' in s or '"""' in s or '\n' in s for s in [word, phonetic, meaning, lesson, sentence, translation])
        output.append("\t".join([word, phonetic, meaning, lesson, sentence, translation]))
    # Split literals to stay below the JVM constant-pool UTF-8 string limit.
    chunks = ["\n".join(output[i:i + 100]) for i in range(0, len(output), 100)]
    literals = ',\n'.join('        """\n' + chunk + '\n        """.trimIndent()' for chunk in chunks)
    code = '''package com.personalieltscoach.data.seed

import com.personalieltscoach.data.local.entity.WordItemEntity
import com.personalieltscoach.data.local.entity.WordSource

/** Generated by scripts/generate_nce2_word_pack.py. Original examples, no textbook prose.
 * Source: https://www.ncego.com/books/words/nce2 (2026-10-01).
 * Duplicate headwords within Book 2 share a card; all lesson references are retained.
 */
object Nce2WordPack {
    const val SOURCE_ENTRY_COUNT = 877
    const val UNIQUE_WORD_COUNT = 851
    const val LESSON_COUNT = 96

    fun words(now: Long): List<WordItemEntity> = rows.asSequence()
        .flatMap { it.lineSequence() }.map(String::trim).filter(String::isNotBlank)
        .map { row ->
            val p = row.split('\\t')
            require(p.size == 6) { "Invalid NCE2 row" }
            WordItemEntity(word = p[0], phonetic = p[1], meaning = p[2], level = p[3],
                example = p[4], exampleTranslation = p[5], source = WordSource.NCE2,
                createdAt = now, updatedAt = now)
        }.toList()

    private val rows = listOf(
''' + literals + '\n    )\n}\n'
    (ROOT / "app/src/main/java/com/personalieltscoach/data/seed/Nce2WordPack.kt").write_text(code, encoding="utf-8")
    print(f"Generated {len(output)} NCE2 cards with original bilingual examples.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-html", type=Path)
    parser.add_argument("--import-only", action="store_true")
    args = parser.parse_args()
    if args.source_html:
        import_source(args.source_html)
    if not args.import_only:
        build()
