package com.personalieltscoach.data.seed

import com.personalieltscoach.data.local.entity.WordItemEntity
import com.personalieltscoach.data.local.entity.WordSource

/** Generated by scripts/generate_nce2_word_pack.py. Original examples, no textbook prose.
 * Source: https://www.ncego.com/books/words/nce2 (2026-10-01).
 * Duplicate headwords within Book 2 share a card; all lesson references are retained.
 */
object Nce2WordPack {
    const val SOURCE_ENTRY_COUNT = 877
    const val UNIQUE_WORD_COUNT = 851
    const val LESSON_COUNT = 96

    fun words(now: Long): List<WordItemEntity> = rows.asSequence()
        .flatMap { it.lineSequence() }.map(String::trim).filter(String::isNotBlank)
        .map { row ->
            val p = row.split('\t')
            require(p.size == 6) { "Invalid NCE2 row" }
            WordItemEntity(word = p[0], phonetic = p[1], meaning = p[2], level = p[3],
                example = p[4], exampleTranslation = p[5], source = WordSource.NCE2,
                createdAt = now, updatedAt = now)
        }.toList()

    private val rows = listOf(
        """
private	/ˈpraɪvət/	adj. 私人的	NCE2 Lesson 1	Could we have a private chat?	我们能单独聊聊吗？
conversation	/ˌkɒnvəˈseɪʃ(ə)n/	n. 谈话	NCE2 Lesson 1	We had a long conversation about work.	我们聊了很久工作上的事。
theatre	/ˈθɪətə(r)/	n. 剧场，戏院	NCE2 Lesson 1	Shall we meet outside the theatre?	我们在剧院外面碰面好吗？
seat	/siːt/	n. 座位	NCE2 Lesson 1	Is this seat taken?	这个座位有人吗？
angry	/ˈæŋɡri/	adj. 生气的	NCE2 Lesson 1	Are you still angry with me?	你还在生我的气吗？
attention	/əˈtenʃ(ə)n/	n. 注意	NCE2 Lesson 1	Pay attention to the road.	注意看路。
angrily	/ˈæŋɡrəli/	adv. 生气地	NCE2 Lesson 1	He put the phone down angrily.	他生气地挂断了电话。
bear	/beə(r)/	v. 容忍	NCE2 Lesson 1	I can't bear this noise.	我受不了这噪声。
business	/ˈbɪznəs/	n. 事	NCE2 Lesson 1	That's none of my business.	那不关我的事。
rudely	/ˈruːdli/	adv. 无礼地，粗鲁地	NCE2 Lesson 1	She spoke rather rudely to the waiter.	她跟服务员说话挺没礼貌的。
play	/pleɪ/	n. 戏	NCE2 Lesson 1	We're going to see a play tonight.	我们今晚要去看一出戏。
loudly	/ˈlaʊdli/	adv. 大声地	NCE2 Lesson 1	Please don't talk so loudly.	请别这么大声说话。
until	/ʌnˈtɪl/	prep. 直到	NCE2 Lesson 2	I'll wait here until six.	我会在这里等到六点。
outside	/ˌaʊtˈsaɪd/	adv. 外面	NCE2 Lesson 2	It's cold outside.	外面很冷。
ring	/rɪŋ/	v. （铃、电话等）响（rang, rung）；n. 圆形竞技场地	NCE2 Lesson 2, NCE2 Lesson 70	Did you hear the doorbell ring?	你听到门铃响了吗？
aunt	/ɑːnt/	n. 姑，姨，婶，舅母	NCE2 Lesson 2	My aunt is coming for lunch.	我姑妈要来吃午饭。
repeat	/rɪˈpiːt/	v. 重复	NCE2 Lesson 2	Could you repeat the address?	你能再说一遍地址吗？
send	/send/	v. 寄 , 送寄	NCE2 Lesson 3	Could you send me the address?	你能把地址发给我吗？
postcard	/ˈpəʊstkɑːd/	n. 明信片	NCE2 Lesson 3	I sent Mum a postcard from Rome.	我从罗马给妈妈寄了张明信片。
spoil	/spɔɪl/	v. 使索然无味, 损坏	NCE2 Lesson 3	Don't spoil the surprise!	别把惊喜提前说出来！
museum	/mjuˈziːəm/	n. 博物馆	NCE2 Lesson 3	The museum is closed on Mondays.	博物馆每周一闭馆。
public	/ˈpʌblɪk/	adj. 公共的	NCE2 Lesson 3	Is there a public toilet nearby?	附近有公共厕所吗？
friendly	/ˈfrendli/	adj. 友好的	NCE2 Lesson 3	Your neighbours seem really friendly.	你的邻居看起来很友好。
waiter	/ˈweɪtə(r)/	n. 服务员, 招待员	NCE2 Lesson 3	Let's ask the waiter for the bill.	我们叫服务员拿账单吧。
lend	/lend/	v. 借给，借出	NCE2 Lesson 3	Could you lend me a pen?	你能借我一支笔吗？
decision	/dɪˈsɪʒ(ə)n/	n. 决定	NCE2 Lesson 3	It's a big decision, so take your time.	这是个重要决定，慢慢考虑。
whole	/həʊl/	adj. 整个的	NCE2 Lesson 3	I've been waiting the whole morning.	我等了一整个上午。
single	/ˈsɪŋɡ(ə)l/	adj. 唯一的, 单一的	NCE2 Lesson 3	There wasn't a single seat left.	一个座位也没剩下。
decide	/dɪˈsaɪd/	v. 决定	NCE2 Lesson 3	Have you had time to decide?	你有时间考虑好了吗？
exciting	/ɪkˈsaɪtɪŋ/	adj. 令人兴奋的	NCE2 Lesson 4	Starting a new job is exciting.	开始一份新工作很令人兴奋。
receive	/rɪˈsiːv/	v. 接收，收到	NCE2 Lesson 4	Did you receive my message?	你收到我的消息了吗？
firm	/fɜːm/	n. 商行，公司	NCE2 Lesson 4	She works for a small law firm.	她在一家小律师事务所工作。
different	/ˈdɪfrənt/	adj. 不同的	NCE2 Lesson 4	Could I try a different size?	我能试试另一个尺码吗？
centre	/ˈsentə(r)/	n. 中心	NCE2 Lesson 4	How far is the town centre?	市中心有多远？
abroad	/əˈbrɔːd/	adv. 在国外	NCE2 Lesson 4	Have you ever worked abroad?	你在国外工作过吗？
pigeon	/ˈpɪdʒɪn/	n. 鸽子	NCE2 Lesson 5	There's a pigeon on the balcony.	阳台上有一只鸽子。
message	/ˈmesɪdʒ/	n. 信息	NCE2 Lesson 5	Could you leave him a message for me?	你能帮我给他留个口信吗？
cover	/ˈkʌvə(r)/	v. 越过	NCE2 Lesson 5	We can cover that distance in an hour.	我们一个小时就能走完那段路。
distance	/ˈdɪstəns/	n. 距离	NCE2 Lesson 5	What's the distance between the two towns?	这两个城镇相距多远？
request	/rɪˈkwest/	n. 要求，请求	NCE2 Lesson 5	I've sent a request for a refund.	我已经提交退款申请了。
spare part	/ˌspeə ˈpɑːt/	n. 备件	NCE2 Lesson 5	We need to order a spare part.	我们需要订购一个备件。
service	/ˈsɜːvɪs/	n. 业务，服务	NCE2 Lesson 5	Is service included in the bill?	账单包含服务费吗？
beggar	/ˈbeɡə(r)/	n. 乞丐	NCE2 Lesson 6	A beggar was sitting outside the station.	车站外坐着一个乞丐。
food	/fuːd/	n. 食物	NCE2 Lesson 6	The food here is really good.	这里的食物真不错。
pocket	/ˈpɒkɪt/	n. 衣服口袋	NCE2 Lesson 6	There's a hole in my pocket.	我的口袋破了个洞。
call	/kɔːl/	v. 拜访，光顾	NCE2 Lesson 6	I'll call at your house after work.	我下班后去你家拜访。
detective	/dɪˈtektɪv/	n. 侦探	NCE2 Lesson 7	The detective asked me a few questions.	那位侦探问了我几个问题。
airport	/ˈeəpɔːt/	n. 机场	NCE2 Lesson 7	What time should we leave for the airport?	我们几点该出发去机场？
expect	/ɪkˈspekt/	v. 预计；期待，等待	NCE2 Lesson 7	What time do you expect to arrive?	你预计几点到？
valuable	/ˈvæljuəb(ə)l/	adj. 贵重的	NCE2 Lesson 7	Don't leave anything valuable in the car.	别把贵重物品留在车里。
parcel	/ˈpɑːs(ə)l/	n. 包裹	NCE2 Lesson 7	Has my parcel arrived yet?	我的包裹到了吗？
diamond	/ˈdaɪmənd/	n. 钻石	NCE2 Lesson 7	Is that a real diamond?	那是真钻石吗？
steal	/stiːl/	v. 偷	NCE2 Lesson 7	Why would anyone steal an old bicycle?	谁会去偷一辆旧自行车呢？
main	/meɪn/	adj. 主要的	NCE2 Lesson 7	The main entrance is on the other side.	正门在另一边。
airfield	/ˈeəfiːld/	n. 飞机起落的场地	NCE2 Lesson 7	There's a small airfield near the village.	村庄附近有一个小型机场。
guard	/ɡɑːd/	n. 守卫，警卫；警戒	NCE2 Lesson 7	The guard checked our tickets.	门卫检查了我们的票。
precious	/ˈpreʃəs/	adj. 珍贵的	NCE2 Lesson 7	This photo is very precious to me.	这张照片对我来说非常珍贵。
stone	/stəʊn/	n. 石子	NCE2 Lesson 7	I've got a stone in my shoe.	我的鞋里进了颗小石子。
sand	/sænd/	n. 沙子	NCE2 Lesson 7	There's sand all over the floor.	地板上到处都是沙子。
competition	/ˌkɒmpəˈtɪʃ(ə)n/	n. 比赛，竞赛	NCE2 Lesson 8	Are you entering the cooking competition?	你要参加烹饪比赛吗？
neat	/niːt/	adj. 整齐的，整洁的	NCE2 Lesson 8	Your handwriting is really neat.	你的字写得真工整。
path	/pɑːθ/	n. 小路，小径	NCE2 Lesson 8	Follow this path to the beach.	沿着这条小路就能到海滩。
wooden	/ˈwʊdn/	adj. 木头的；adj. 木制的	NCE2 Lesson 8, NCE2 Lesson 46	I like that wooden table.	我喜欢那张木桌。
pool	/puːl/	n. 水池	NCE2 Lesson 8	Does the hotel have a pool?	酒店有游泳池吗？
welcome	/ˈwelkəm/	n. 欢迎；v. 欢迎	NCE2 Lesson 9	Thanks for the warm welcome.	谢谢你们的热情欢迎。
crowd	/kraʊd/	n. 人群	NCE2 Lesson 9	I couldn't see her in the crowd.	我在人群里没看见她。
gather	/ˈɡæðə(r)/	v. 聚集；v. 收庄稼	NCE2 Lesson 9, NCE2 Lesson 76	Let's gather outside the main entrance.	我们在正门外集合吧。
hand	/hænd/	n. （表或机器的）指针	NCE2 Lesson 9	The second hand on my watch has stopped.	我手表上的秒针不走了。
shout	/ʃaʊt/	v. 喊叫	NCE2 Lesson 9	You don't need to shout; I can hear you.	你不必喊，我听得见。
refuse	/rɪˈfjuːz/	v. 拒绝	NCE2 Lesson 9	It's hard to refuse free cake.	免费的蛋糕很难拒绝。
laugh	/lɑːf/	v. 笑	NCE2 Lesson 9	That story always makes me laugh.	那个故事总能逗笑我。
jazz	/dʒæz/	n. 爵士音乐	NCE2 Lesson 10	Do you listen to jazz?	你听爵士乐吗？
musical	/ˈmjuːzɪk(ə)l/	adj. 音乐的；adj. 精通音乐的	NCE2 Lesson 10, NCE2 Lesson 42	Can you play a musical instrument?	你会演奏乐器吗？
instrument	/ˈɪnstrəmənt/	n. 乐器	NCE2 Lesson 10	Which instrument would you like to learn?	你想学哪种乐器？
clavichord	/ˈklævɪkɔːd/	n. 古钢琴	NCE2 Lesson 10	Have you ever heard a clavichord?	你听过古钢琴的声音吗？
recently	/ˈriːs(ə)ntli/	adv. 最近	NCE2 Lesson 10	I moved here recently.	我最近才搬到这里。
damage	/ˈdæmɪdʒ/	v. 损坏；v. 毁坏	NCE2 Lesson 10, NCE2 Lesson 66	Be careful not to damage the floor.	小心别弄坏地板。
key	/kiː/	n. 琴键	NCE2 Lesson 10	One key on this piano is stuck.	这架钢琴上有一个琴键卡住了。
string	/strɪŋ/	n. （乐器的）弦	NCE2 Lesson 10	A string on my guitar broke.	我的吉他断了一根弦。
shock	/ʃɒk/	v. 使不悦或生气，震惊	NCE2 Lesson 10	The ending will shock you.	这个结局会让你震惊。
allow	/əˈlaʊ/	v. 允许，让	NCE2 Lesson 10	Do they allow dogs in this café?	这家咖啡馆允许带狗吗？
touch	/tʌtʃ/	v. 触摸	NCE2 Lesson 10	Please don't touch the paint; it's still wet.	请别碰油漆，还没干。
turn	/tɜːn/	n. 行为，举止	NCE2 Lesson 11	You did me a good turn today.	你今天帮了我一个忙。
deserve	/dɪˈzɜːv/	v. 应得到，值得	NCE2 Lesson 11	You deserve a break.	你该休息一下了。
lawyer	/ˈlɔɪə(r)/	n. 律师	NCE2 Lesson 11	I need to speak to a lawyer.	我需要咨询一位律师。
bank	/bæŋk/	n. 银行	NCE2 Lesson 11	Is the bank open on Saturdays?	银行星期六营业吗？
salary	/ˈsæləri/	n. 工资	NCE2 Lesson 11	Does the job offer a good salary?	这份工作的薪水高吗？
immediately	/ɪˈmiːdiətli/	adv. 立刻	NCE2 Lesson 11	Please call me immediately.	请马上给我打电话。
luck	/lʌk/	n. 运气，幸运	NCE2 Lesson 12	Good luck with your interview!	祝你面试顺利！
captain	/ˈkæptɪn/	n. 船长	NCE2 Lesson 12	The captain says we'll arrive at noon.	船长说我们中午会到。
sail	/seɪl/	v. 航行	NCE2 Lesson 12	What time does the ferry sail?	渡轮几点开？
harbour	/ˈhɑːbə(r)/	n. 港口	NCE2 Lesson 12	Let's walk down to the harbour.	我们走去港口吧。
proud	/praʊd/	adj. 自豪	NCE2 Lesson 12	I'm really proud of you.	我真为你感到骄傲。
important	/ɪmˈpɔːt(ə)nt/	adj. 重要的	NCE2 Lesson 12	It's important to ask if you don't understand.	不懂就问，这很重要。
group	/ɡruːp/	n. 小组，团体	NCE2 Lesson 13	Would you like to join our study group?	你想加入我们的学习小组吗？
pop singer	/pɒp ˈsɪŋə(r)/	n. 流行歌手	NCE2 Lesson 13	My cousin wants to be a pop singer.	我表妹想当流行歌手。
club	/klʌb/	n. 俱乐部	NCE2 Lesson 13	I joined a local running club.	我加入了当地的跑步俱乐部。
performance	/pəˈfɔːməns/	n. 演出	NCE2 Lesson 13	Did you enjoy the performance last night?	你喜欢昨晚的演出吗？
occasion	/əˈkeɪʒ(ə)n/	n. 场合	NCE2 Lesson 13	Are you saving that dress for a special occasion?	你留着那条裙子是准备在特殊场合穿吗？
experience	/ɪkˈspɪəriəns/	n. 经历	NCE2 Lesson 14, NCE2 Lesson 31	Camping in the rain was quite an experience.	雨中露营真是一次难忘的经历。
        """.trimIndent(),
        """
wave	/weɪv/	v. 招手	NCE2 Lesson 14	Wave to me when you see me.	看到我时向我挥挥手。
lift	/lɪft/	n. 搭便车（give someone a lift）	NCE2 Lesson 14	Could you give me a lift home?	你能让我搭车回家吗？
reply	/rɪˈplaɪ/	v. 回答	NCE2 Lesson 14	I'll reply to your email tonight.	我今晚会回复你的邮件。
language	/ˈlæŋɡwɪdʒ/	n. 语言	NCE2 Lesson 14	What language do you speak at home?	你在家说什么语言？
journey	/ˈdʒɜːni/	n. 旅行	NCE2 Lesson 14	How was your journey?	你一路上还顺利吗？
amusing	/əˈmjuːzɪŋ/	adj. 好笑的，有趣的	NCE2 Lesson 14	I found his story quite amusing.	我觉得他的故事挺好笑的。
secretary	/ˈsekrət(ə)ri/	n. 秘书	NCE2 Lesson 15	Please leave a message with my secretary.	请给我的秘书留个口信。
nervous	/ˈnɜːvəs/	adj. 精神紧张的	NCE2 Lesson 15	I'm nervous about the interview.	我为面试感到紧张。
afford	/əˈfɔːd/	v. 负担得起	NCE2 Lesson 15	I can't afford a new car this year.	我今年买不起新车。
weak	/wiːk/	adj. 弱的	NCE2 Lesson 15	My legs feel weak after that long climb.	爬了那么久的山，我的腿都发软了。
interrupt	/ˌɪntəˈrʌpt/	v. 插话，打断	NCE2 Lesson 15	Sorry to interrupt, but your taxi is here.	抱歉打断一下，你的出租车到了。
park	/pɑːk/	v. 停放（汽车）	NCE2 Lesson 16	Can I park here?	我能在这里停车吗？
traffic	/ˈtræfɪk/	n. 交通	NCE2 Lesson 16	The traffic is terrible this morning.	今天早上的交通堵得厉害。
ticket	/ˈtɪkɪt/	n. 交通违规罚款单	NCE2 Lesson 16	I got a parking ticket yesterday.	我昨天收到了一张违章停车罚单。
note	/nəʊt/	n. 便条	NCE2 Lesson 16	I've left you a note on the fridge.	我在冰箱上给你留了张便条。
area	/ˈeəriə/	n. 地段	NCE2 Lesson 16	Do you know this area well?	你熟悉这一带吗？
sign	/saɪn/	n. 指示牌；v. 签字	NCE2 Lesson 16, NCE2 Lesson 54	The sign says the shop is closed today.	牌子上写着商店今天不营业。
reminder	/rɪˈmaɪndə(r)/	n. 提示	NCE2 Lesson 16	Thanks for the reminder.	谢谢你提醒我。
fail	/feɪl/	v. 未能，忘记做（fail to do）	NCE2 Lesson 16	Don't fail to let me know if you're late.	如果你要迟到，可别忘了告诉我。
obey	/əˈbeɪ/	v. 服从	NCE2 Lesson 16	We all have to obey the rules.	我们都得遵守规则。
polite	/pəˈlaɪt/	adj. 有礼貌的	NCE2 Lesson 16	It was polite of him to ask first.	他先问了一声，很有礼貌。
appear	/əˈpɪə(r)/	v. 登场，扮演	NCE2 Lesson 17	She's going to appear in a new play.	她将出演一部新戏。
stage	/steɪdʒ/	n. 舞台	NCE2 Lesson 17	Can you see the stage from here?	你从这里能看到舞台吗？
bright	/braɪt/	adj. 鲜艳的	NCE2 Lesson 17	That bright yellow coat really suits you.	那件鲜黄色外套真适合你。
stocking	/ˈstɒkɪŋ/	n. 长筒袜	NCE2 Lesson 17	There's a hole in this stocking.	这只长筒袜上有个洞。
sock	/sɒk/	n. 短袜	NCE2 Lesson 17	Have you seen my other sock?	你看到我的另一只短袜了吗？
pub	/pʌb/	n. 酒吧，小酒馆	NCE2 Lesson 18	Let's meet at the pub after work.	我们下班后在酒吧见吧。
landlord	/ˈlændlɔːd/	n. 酒吧老板；房东	NCE2 Lesson 18	The landlord of the pub knows everyone here.	这家酒吧的老板认识这里所有的人。
bill	/bɪl/	n. 帐单	NCE2 Lesson 18	Could we have the bill, please?	请给我们账单，好吗？
hurry	/ˈhʌri/	v. 赶快，匆忙行事；n. 匆忙	NCE2 Lesson 19	There's no need to hurry.	不用着急。
ticket office	/ˈtɪkɪt ˈɒfɪs/	n. 售票处	NCE2 Lesson 19	Where's the ticket office?	售票处在哪里？
pity	/ˈpɪti/	n. 令人遗憾的事	NCE2 Lesson 19	It's a pity you can't come with us.	真遗憾，你不能和我们一起去。
exclaim	/ɪkˈskleɪm/	v. 大声说	NCE2 Lesson 19	The surprise made her exclaim in delight.	这个惊喜让她高兴地叫了出来。
return	/rɪˈtɜːn/	v. 退回	NCE2 Lesson 19	Can I return this shirt without a receipt?	没有收据，我能退这件衬衫吗？
sadly	/ˈsædli/	adv. 悲哀地，丧气地	NCE2 Lesson 19	She smiled sadly and walked away.	她伤心地笑了笑，走开了。
fisherman	/ˈfɪʃəmən/	n. 钓鱼人，渔民	NCE2 Lesson 20	We bought fresh fish from a local fisherman.	我们从当地渔民那里买了新鲜的鱼。
boot	/buːt/	n. 靴子	NCE2 Lesson 20	My left boot is leaking.	我左脚的靴子漏水了。
waste	/weɪst/	n. 浪费	NCE2 Lesson 20	Throwing all this food away is such a waste.	把这些食物全扔掉太浪费了。
realize	/ˈriːəlaɪz/	v. 意识到	NCE2 Lesson 20	I didn't realize you were waiting for me.	我没意识到你在等我。
catch	/kætʃ/	v. 抓到	NCE2 Lesson 20	Did you catch any fish?	你钓到鱼了吗？
mad	/mæd/	adj. 发疯	NCE2 Lesson 21	That noise is driving me mad.	那噪声快把我逼疯了。
reason	/ˈriːz(ə)n/	n. 原因	NCE2 Lesson 21	Is there a reason why the appointment was cancelled?	预约取消有什么原因吗？
sum	/sʌm/	n. 一笔钱；总数	NCE2 Lesson 21	That's a large sum of money.	那是一大笔钱。
determined	/dɪˈtɜːmɪnd/	adj. 坚定的，下决心的	NCE2 Lesson 21	She's determined to finish the course.	她下定决心要完成这门课程。
dream	/driːm/	v. 做梦，梦想	NCE2 Lesson 22	I often dream about travelling around New Zealand.	我经常梦想环游新西兰。
age	/eɪdʒ/	n. 年龄	NCE2 Lesson 22	We're about the same age.	我们年龄差不多。
channel	/ˈtʃæn(ə)l/	n. 海峡	NCE2 Lesson 22	This channel separates the two islands.	这条海峡把两座岛分开了。
throw	/θrəʊ/	v. 扔，抛	NCE2 Lesson 22	Please don't throw batteries in the general waste bin.	请不要把电池扔进普通垃圾桶。
complete	/kəmˈpliːt/	v. 完成	NCE2 Lesson 23	Please complete the form before Friday.	请在星期五之前填完表格。
modern	/ˈmɒd(ə)n/	adj. 新式的，与以往不同的	NCE2 Lesson 23	The kitchen is small but modern.	厨房虽小，但很现代。
strange	/streɪndʒ/	adj. 奇怪的	NCE2 Lesson 23	There's a strange smell coming from the fridge.	冰箱里传出一股怪味。
district	/ˈdɪstrɪkt/	n. 地区	NCE2 Lesson 23	Which district do you live in?	你住在哪个区？
manager	/ˈmænɪdʒə(r)/	n. 经理	NCE2 Lesson 24	I'll ask the manager if we can change it.	我去问问经理能不能换。
upset	/ˌʌpˈset/	adj. 不安	NCE2 Lesson 24	You seem upset. What's wrong?	你看起来心烦意乱，怎么了？
sympathetic	/ˌsɪmpəˈθetɪk/	adj. 表示同情的	NCE2 Lesson 24	My boss was very sympathetic when I explained.	我解释后，老板很体谅我。
complain	/kəmˈpleɪn/	v. 抱怨	NCE2 Lesson 24, NCE2 Lesson 38	I'd like to complain about the noise.	我想投诉噪声问题。
wicked	/ˈwɪkɪd/	adj. 很坏的，邪恶的	NCE2 Lesson 24	The story has a wicked queen.	故事里有个邪恶的王后。
contain	/kənˈteɪn/	v. 包含，内装	NCE2 Lesson 24	Does this sauce contain nuts?	这种酱汁含坚果吗？
honesty	/ˈɒnəsti/	n. 诚实	NCE2 Lesson 24	I appreciate your honesty.	我感谢你的坦诚。
railway	/ˈreɪlweɪ/	n. 铁路	NCE2 Lesson 25	The railway runs behind our house.	铁路从我们房子后面经过。
porter	/ˈpɔːtə(r)/	n. 搬运工	NCE2 Lesson 25	The porter helped us with our bags.	搬运工帮我们拿了行李。
foreigner	/ˈfɒrənə(r)/	n. 外国人	NCE2 Lesson 25	As a foreigner, I had to apply for a visa.	作为外国人，我必须申请签证。
wonder	/ˈwʌndə(r)/	v. 想知道；感到疑惑	NCE2 Lesson 25	I wonder if the shop is still open.	不知道那家商店还开不开门。
several	/ˈsevrəl/	pron. 几个	NCE2 Lesson 25	I've tried several, but none fit.	我试过好几个，但都不合适。
quantifier	/ˈkwɒntɪfaɪə/	n. 数量词	NCE2 Lesson 25	Is "some" a quantifier?	“some”是数量词吗？
art	/ɑːt/	n. 艺术	NCE2 Lesson 26	We went to an art gallery yesterday.	我们昨天去了一家美术馆。
critic	/ˈkrɪtɪk/	n. 评论家	NCE2 Lesson 26	The film critic gave it a great review.	那位影评人给了这部电影很高的评价。
paint	/peɪnt/	v. 画	NCE2 Lesson 26	I'd love to learn to paint portraits.	我很想学画肖像。
pretend	/prɪˈtend/	v. 假装	NCE2 Lesson 26	Don't pretend you didn't hear me.	别假装没听见我说话。
pattern	/ˈpæt(ə)n/	n. 图案	NCE2 Lesson 26	I love the pattern on those curtains.	我很喜欢那些窗帘上的图案。
curtain	/ˈkɜːt(ə)n/	n. 窗帘，幕布	NCE2 Lesson 26	Could you pull the curtain across?	你能把窗帘拉上吗？
material	/məˈtɪəriəl/	n. 材料	NCE2 Lesson 26	What material is this jacket made of?	这件夹克是什么材料做的？
appreciate	/əˈpriːʃieɪt/	v. 鉴赏	NCE2 Lesson 26	You don't have to be an expert to appreciate art.	你不必是专家也能欣赏艺术。
notice	/ˈnəʊtɪs/	v. 注意到；n. 告示	NCE2 Lesson 26, NCE2 Lesson 74	Did you notice the new curtains?	你注意到新窗帘了吗？
whether	/ˈweðə(r)/	conj. 是否	NCE2 Lesson 26	I don't know whether he's coming.	我不知道他来不来。
hang	/hæŋ/	v. 悬挂，吊	NCE2 Lesson 26	You can hang your coat here.	你可以把外套挂在这里。
critically	/ˈkrɪtɪkli/	adv. 批评地	NCE2 Lesson 26	She looked critically at my painting.	她用挑剔的眼光看着我的画。
upside down	/ˌʌpsaɪd ˈdaʊn/	adv. 上下颠倒地，倒置地	NCE2 Lesson 26	You're holding the map upside down.	你把地图拿倒了。
upside	/ˈʌpsaɪd/	n. 优势	NCE2 Lesson 26	The upside is that we can walk to work.	好处是我们可以走路上班。
tent	/tent/	n. 帐篷	NCE2 Lesson 27	Can you help me put up the tent?	你能帮我搭帐篷吗？
field	/fiːld/	n. 田地，田野	NCE2 Lesson 27	There's a field of sheep behind the house.	房子后面有一片养着羊的田地。
smell	/smel/	v. 闻起来	NCE2 Lesson 27	These flowers smell lovely.	这些花闻起来真香。
wonderful	/ˈwʌndəf(ə)l/	adj. 极好的	NCE2 Lesson 27	We had a wonderful time.	我们玩得非常开心。
campfire	/ˈkæmpfaɪə(r)/	n. 营火，篝火	NCE2 Lesson 27	We sat around the campfire after dinner.	晚饭后，我们围坐在篝火旁。
creep	/kriːp/	v. 悄悄移动；爬行	NCE2 Lesson 27	Try to creep past without waking the baby.	尽量悄悄走过去，别吵醒宝宝。
sleeping bag	/ˈsliːpɪŋ bæɡ/	n. 睡袋	NCE2 Lesson 27	Is your sleeping bag warm enough?	你的睡袋够暖和吗？
comfortable	/ˈkʌmftəb(ə)l/	adj. 舒适的，安逸的	NCE2 Lesson 27	Make yourself comfortable.	请随意，坐舒服些。
soundly	/ˈsaʊndli/	adv. 香甜地	NCE2 Lesson 27	I slept soundly after the long walk.	走了那么远的路后，我睡得很沉。
leap	/liːp/	v. 跳跃，跳起	NCE2 Lesson 27	Can you leap over that puddle?	你能跳过那个水坑吗？
heavily	/ˈhevɪli/	adv. 大量地	NCE2 Lesson 27	It was raining heavily when we left.	我们离开时雨下得很大。
stream	/striːm/	n. 小溪	NCE2 Lesson 27	There's a little stream behind the campsite.	露营地后面有一条小溪。
form	/fɔːm/	v. 形成	NCE2 Lesson 27	Ice can form on the road overnight.	路面可能在夜间结冰。
wind	/waɪnd/	v. 蜿蜒	NCE2 Lesson 27	The narrow roads wind through the hills.	狭窄的道路蜿蜒穿过山间。
right	/raɪt/	adv. 正好	NCE2 Lesson 27	The bus stop is right outside.	公交车站就在外面。
rare	/reə(r)/	adj. 罕见的	NCE2 Lesson 28	It's rare to see snow here.	这里很少下雪。
ancient	/ˈeɪnʃənt/	adj. 古代的，古老的	NCE2 Lesson 28	We visited an ancient temple.	我们参观了一座古老的寺庙。
myth	/mɪθ/	n. 神话故事	NCE2 Lesson 28	Have you heard the myth about that mountain?	你听说过关于那座山的神话吗？
trouble	/ˈtrʌb(ə)l/	n. 麻烦	NCE2 Lesson 28	Sorry to cause you so much trouble.	抱歉给你添了这么多麻烦。
effect	/ɪˈfekt/	n. 结果，效果	NCE2 Lesson 28	The new curtains have a lovely effect.	新窗帘装上去效果很好。
Medusa	/mɪˈdjuːzə/	n. 美杜莎（希腊神话中的蛇发女怪）	NCE2 Lesson 28	Is that a picture of Medusa?	那是美杜莎的画像吗？
        """.trimIndent(),
        """
Gorgon	/ˈɡɔːɡən/	n. （古希腊神话）3 位蛇发女怪之一（凡见其貌者都会变成石头）	NCE2 Lesson 28	In the myth, Medusa is a Gorgon.	在神话中，美杜莎是一位蛇发女怪。
taxi	/ˈtæksi/	n. 出租汽车	NCE2 Lesson 29	Shall we get a taxi home?	我们打车回家好吗？
Pilatus Porter		n. 皮拉图斯波特飞机（机型名称，音标待核对）	NCE2 Lesson 29	That's a Pilatus Porter over there.	那边是一架皮拉图斯波特飞机。
land	/lænd/	v. 着陆 (不及物)	NCE2 Lesson 29	What time does your flight land?	你的航班几点降落？
plough	/plaʊ/	v. 耕地	NCE2 Lesson 29	They plough this field every spring.	他们每年春天都犁这块田。
lonely	/ˈləʊnli/	adj. 偏僻的, 人迹罕见的(地方)	NCE2 Lesson 29	We stayed in a lonely cottage in the hills.	我们住在山间一座偏僻的小屋里。
Welsh	/welʃ/	adj. 威尔士的	NCE2 Lesson 29	My neighbour has a Welsh accent.	我的邻居带有威尔士口音。
roof	/ruːf/	n. 楼顶 (从外面看)	NCE2 Lesson 29	The roof needs repairing.	屋顶需要修理了。
block	/blɒk/	n. 块, 一座大楼；v. 堵	NCE2 Lesson 29, NCE2 Lesson 47	She lives in that block of flats.	她住在那栋公寓楼里。
flat	/flæt/	n. 公寓房	NCE2 Lesson 29	We're looking for a flat near the station.	我们在找车站附近的公寓。
desert	/dɪˈzɜːt/	v. 废弃	NCE2 Lesson 29	People began to desert the village after the factory closed.	工厂关闭后，人们开始离开那个村庄。
polo	/ˈpəʊləʊ/	n. 马球；water polo 指水球	NCE2 Lesson 30	Have you ever played water polo?	你打过水球吗？
Wayle	/weɪl/	n. 威尔（课文中的河名）	NCE2 Lesson 30	The story takes place by the River Wayle.	这个故事发生在威尔河边。
cut	/kʌt/	v. 穿过	NCE2 Lesson 30	Let's cut across the park.	我们抄近路穿过公园吧。
row	/rəʊ/	v. 划（船）	NCE2 Lesson 30	Can you row us back to the shore?	你能划船把我们送回岸边吗？
kick	/kɪk/	v. 踢	NCE2 Lesson 30	Don't kick the ball towards the road.	别把球踢向马路。
towards	/təˈwɔːdz/	prep. 朝，向；prep. 向，朝；接近	NCE2 Lesson 30, NCE2 Lesson 33	She walked towards the station.	她朝车站走去。
nearly	/ˈnɪəli/	adv. 几乎	NCE2 Lesson 30	It's nearly six, so the shop may be closed.	快六点了，商店可能关门了。
sight	/saɪt/	n. 眼界，视域；v. 见到	NCE2 Lesson 30, NCE2 Lesson 82	Keep the children in sight.	别让孩子们离开你的视线。
retire	/rɪˈtaɪə(r)/	v. 退休	NCE2 Lesson 31	My supervisor plans to retire next year.	我的主管打算明年退休。
company	/ˈkʌmpəni/	n. 公司	NCE2 Lesson 31	How long have you been with this company?	你在这家公司工作多久了？
bicycle	/ˈbaɪsɪk(ə)l/	n. 自行车	NCE2 Lesson 31	Can I borrow your bicycle?	我能借你的自行车吗？
save	/seɪv/	v. 积蓄	NCE2 Lesson 31	I'm trying to save enough for a deposit.	我正努力攒够押金。
workshop	/ˈwɜːkʃɒp/	n. 车间	NCE2 Lesson 31	The tools are in the workshop.	工具在车间里。
helper	/ˈhelpə(r)/	n. 帮手，助手	NCE2 Lesson 31	We need one more helper in the kitchen.	厨房里还需要一个帮手。
employ	/ɪmˈplɔɪ/	v. 雇佣	NCE2 Lesson 31	How many people does the shop employ?	这家店雇了多少人？
grandson	/ˈɡrænsʌn/	n. 孙子	NCE2 Lesson 31	Her grandson starts school next week.	她的孙子下周开始上学。
success	/səkˈses/	n. 成功	NCE2 Lesson 31	The party was a big success.	聚会办得非常成功。
work	/wɜːk/	n. 工作	NCE2 Lesson 31	What time do you finish work?	你几点下班？
once	/wʌns/	adv. 曾经，以前	NCE2 Lesson 32	I once lived above a bakery.	我曾经住在一家面包店楼上。
temptation	/tempˈteɪʃ(ə)n/	n. 诱惑	NCE2 Lesson 32	I couldn't resist the temptation to buy another cake.	我忍不住又买了一个蛋糕。
article	/ˈɑːtɪk(ə)l/	n. 物品，东西	NCE2 Lesson 32	Each article in the shop has a price tag.	店里的每件物品都贴着价签。
wrap	/ræp/	v. 包裹	NCE2 Lesson 32	Could you wrap this as a gift?	你能帮我把这个包装成礼物吗？
simply	/ˈsɪmpli/	adv. 仅仅	NCE2 Lesson 32	I wasn't angry; I was simply tired.	我没生气，只是累了。
arrest	/əˈrest/	v. 逮捕	NCE2 Lesson 32	Did the police arrest anyone?	警方逮捕了什么人吗？
darkness	/ˈdɑːknəs/	n. 黑暗	NCE2 Lesson 33	We couldn't see anything in the darkness.	黑暗中，我们什么也看不见。
explain	/ɪkˈspleɪn/	v. 解释，叙述	NCE2 Lesson 33	Could you explain how this works?	你能解释一下这是怎么用的吗？
coast	/kəʊst/	n. 海滨	NCE2 Lesson 33	We're spending the weekend on the coast.	我们要去海边过周末。
storm	/stɔːm/	n. 暴风雨	NCE2 Lesson 33	The storm kept me awake all night.	暴风雨让我一整晚没睡。
rock	/rɒk/	n. 岩石，礁石	NCE2 Lesson 33	Watch out for that rock.	小心那块岩石。
shore	/ʃɔː(r)/	n. 海岸	NCE2 Lesson 33	Let's stay close to the shore.	我们别离岸太远。
light	/laɪt/	n. 灯光	NCE2 Lesson 33	Could you turn on the light?	你能把灯打开吗？
ahead	/əˈhed/	adv. 在前面	NCE2 Lesson 33	There's a petrol station just ahead.	前面不远就有一家加油站。
cliff	/klɪf/	n. 峭壁	NCE2 Lesson 33	Don't stand so close to the cliff edge.	别站得离悬崖边那么近。
struggle	/ˈstrʌɡ(ə)l/	v. 挣扎	NCE2 Lesson 33	I struggle to stay awake after lunch.	午饭后，我很难保持清醒。
hospital	/ˈhɒspɪt(ə)l/	n. 医院	NCE2 Lesson 33	Which hospital does your sister work at?	你姐姐在哪家医院工作？
station	/ˈsteɪʃ(ə)n/	n. （警察）局	NCE2 Lesson 34	We reported it at the police station.	我们去警察局报案了。
most	/məʊst/	adv. 相当，非常	NCE2 Lesson 34	That was most kind of you.	你真是太好了。
while	/waɪl/	n. 一段时间	NCE2 Lesson 35	I haven't seen you for a while.	我有一阵子没见到你了。
regret	/rɪˈɡret/	v. 后悔	NCE2 Lesson 35	I regret selling my old guitar.	我后悔卖掉了旧吉他。
far	/fɑː(r)/	adv. 非常	NCE2 Lesson 35	This jacket is far too expensive.	这件夹克实在太贵了。
rush	/rʌʃ/	v. 冲	NCE2 Lesson 35	Don't rush across the road.	不要冲过马路。
act	/ækt/	v. 行动	NCE2 Lesson 35	We need to act quickly.	我们需要迅速采取行动。
straight	/streɪt/	adv. 径直	NCE2 Lesson 35	Go straight home after school.	放学后直接回家。
fright	/fraɪt/	n. 害怕	NCE2 Lesson 35	You gave me a fright!	你吓了我一跳！
battered	/ˈbætəd/	adj. 撞坏的	NCE2 Lesson 35	He arrived in a battered old van.	他开着一辆破旧的货车来了。
shortly	/ˈʃɔːtli/	adv. 很快，不久	NCE2 Lesson 35	Your food will be ready shortly.	你的饭菜很快就好。
afterwards	/ˈɑːftəwədz/	adv. 以后	NCE2 Lesson 35	Shall we get a coffee afterwards?	之后我们喝杯咖啡好吗？
record	/ˈrekɔːd/	n. 记录	NCE2 Lesson 36	Keep a record of what you spend.	把你的花销记下来。
strong	/strɒŋ/	adj. 强壮的	NCE2 Lesson 36	You need to be strong to carry that.	你得有力气才搬得动那个。
swimmer	/ˈswɪmə(r)/	n. 游泳运动员	NCE2 Lesson 36	I'm not a very good swimmer.	我游泳不太好。
succeed	/səkˈsiːd/	v. 成功	NCE2 Lesson 36	You'll need practice if you want to succeed.	想成功，你就需要练习。
train	/treɪn/	v. 训练	NCE2 Lesson 36	Where do you train for the race?	你在哪里为比赛训练？
anxiously	/ˈæŋkʃəsli/	adv. 焦急地	NCE2 Lesson 36	She waited anxiously for the results.	她焦急地等待结果。
intend	/ɪnˈtend/	v. 打算	NCE2 Lesson 36	How long do you intend to stay?	你打算待多久？
solid	/ˈsɒlɪd/	adj. 固体的，硬的	NCE2 Lesson 36	This table is made of solid wood.	这张桌子是实木做的。
Olympic	/əˈlɪmpɪk/	adj. 奥林匹克的	NCE2 Lesson 37	Did you watch the Olympic swimming final?	你看了奥运会游泳决赛吗？
hold	/həʊld/	v. 召开	NCE2 Lesson 37	Can we hold the meeting online?	我们能在线上开会吗？
government	/ˈɡʌvənmənt/	n. 政府	NCE2 Lesson 37	Is this a government website?	这是政府的网站吗？
immense	/ɪˈmens/	adj. 巨大的	NCE2 Lesson 37	Finishing the project was an immense relief.	项目完成让我大大松了一口气。
stadium	/ˈsteɪdiəm/	n. 露天体育场	NCE2 Lesson 37	The stadium is next to the station.	体育场就在车站旁边。
standard	/ˈstændəd/	n. 标准	NCE2 Lesson 37	The work isn't up to the required standard.	这项工作没有达到要求的标准。
capital	/ˈkæpɪt(ə)l/	n. 首都	NCE2 Lesson 37	What's the capital of New Zealand?	新西兰的首都是哪里？
fantastic	/fænˈtæstɪk/	adj. 巨大的	NCE2 Lesson 37	They spent a fantastic amount on that house.	他们在那栋房子上花了一大笔钱。
design	/dɪˈzaɪn/	v. 设计	NCE2 Lesson 37	She helped design this room.	她参与了这个房间的设计。
except	/ɪkˈsept/	prep. 除了	NCE2 Lesson 38	The office is open every day except Sunday.	除星期天外，办公室每天都开放。
Mediterranean	/ˌmedɪtəˈreɪniən/	n. 地中海	NCE2 Lesson 38	We sailed across the Mediterranean last summer.	去年夏天，我们乘船穿越了地中海。
continually	/kənˈtɪnjuəli/	adv. 不断地	NCE2 Lesson 38	The bus times are continually changing.	公交车时刻总是在变。
bitterly	/ˈbɪtəli/	adv. 刺骨地	NCE2 Lesson 38	It's bitterly cold outside.	外面冷得刺骨。
sunshine	/ˈsʌnʃaɪn/	n. 阳光	NCE2 Lesson 38	Let's sit outside in the sunshine.	我们到外面晒着太阳坐一会儿吧。
settle	/ˈset(ə)l/	v. 安顿	NCE2 Lesson 38	It took us a few weeks to settle in.	我们花了几个星期才安顿下来。
though	/ðəʊ/	conj. 虽然、尽管	NCE2 Lesson 38	I'll come, though I can't stay long.	我会来，不过待不了多久。
operation	/ˌɒpəˈreɪʃ(ə)n/	n. 手术	NCE2 Lesson 39	My aunt is recovering from an operation.	我姑妈正在术后恢复中。
successful	/səkˈsesf(ə)l/	adj. 成功的	NCE2 Lesson 39	Was your application successful?	你的申请成功了吗？
following	/ˈfɒləʊɪŋ/	adj. 下一个	NCE2 Lesson 39	We came back the following day.	我们第二天就回来了。
patient	/ˈpeɪʃ(ə)nt/	n. 病人	NCE2 Lesson 39	The doctor is with another patient.	医生正在给另一位病人看病。
alone	/əˈləʊn/	adj. 独自的	NCE2 Lesson 39	Are you alone in the house?	房子里只有你一个人吗？
exchange	/ɪksˈtʃeɪndʒ/	n. （电话的）交换台	NCE2 Lesson 39	The old telephone exchange is now a café.	旧电话交换站现在是一家咖啡馆。
inquire	/ɪnˈkwaɪə(r)/	v. 询问，打听	NCE2 Lesson 39	I'm calling to inquire about the course.	我打电话是想了解一下这门课程。
certain	/ˈsɜːt(ə)n/	adj. 某个	NCE2 Lesson 39	A certain person keeps borrowing my pen.	某个人老是借我的笔。
caller	/ˈkɔːlə(r)/	n. 打电话的人	NCE2 Lesson 39	The caller didn't leave a name.	来电的人没有留下姓名。
relative	/ˈrelətɪv/	n. 亲戚	NCE2 Lesson 39	Is she a relative of yours?	她是你的亲戚吗？
hostess	/ˈhəʊstəs/	n. 女主人	NCE2 Lesson 40	Our hostess made us feel at home.	女主人让我们感到像在自己家一样自在。
unsmiling	/ˌʌnˈsmaɪlɪŋ/	adj. 不笑的，严肃的	NCE2 Lesson 40	The receptionist was polite but unsmiling.	接待员很有礼貌，但没有笑容。
tight	/taɪt/	adj. 紧身的	NCE2 Lesson 40	These trousers are a bit tight around the waist.	这条裤子的腰有点紧。
fix	/fɪks/	v. 凝视	NCE2 Lesson 40	Try to fix your eyes on one point.	试着把目光集中在一个点上。
globe	/ɡləʊb/	n. 地球	NCE2 Lesson 40	People watched the match across the globe.	世界各地的人都看了这场比赛。
despair	/dɪˈspeə(r)/	n. 绝望	NCE2 Lesson 40	I nearly gave up in despair.	我绝望得几乎放弃了。
rude	/ruːd/	adj. 无礼的	NCE2 Lesson 41	I didn't mean to be rude.	我不是有意无礼的。
mirror	/ˈmɪrə(r)/	n. 镜子	NCE2 Lesson 41	Have a look in the mirror.	照照镜子吧。
        """.trimIndent(),
        """
hole	/həʊl/	n. 孔	NCE2 Lesson 41	There's a hole in your sleeve.	你的袖子上有个洞。
remark	/rɪˈmɑːk/	v. 评说；n. 评论；言语	NCE2 Lesson 41, NCE2 Lesson 70	He made a rude remark about my cooking.	他说了一句很无礼的话，嫌我的菜做得不好。
remind	/rɪˈmaɪnd/	v. 提醒	NCE2 Lesson 41	Could you remind me to call Mum?	你能提醒我给妈妈打电话吗？
lighthouse	/ˈlaɪthaʊs/	n. 灯塔	NCE2 Lesson 41	You can see the lighthouse from here.	从这里可以看到灯塔。
market	/ˈmɑːkɪt/	n. 市场，集市	NCE2 Lesson 42	Let's buy some fruit at the market.	我们去市场买点水果吧。
snake charmer	/ˈsneɪk tʃɑːmə(r)/	n. 玩蛇者（通常借音乐控制）	NCE2 Lesson 42	We saw a snake charmer at the fair.	我们在集市上看到了耍蛇人。
pipe	/paɪp/	n. （吹奏的）管乐器	NCE2 Lesson 42	He played a tune on a wooden pipe.	他用木管笛吹了一段曲子。
tune	/tjuːn/	n. 曲调	NCE2 Lesson 42	I know the tune, but not the words.	我知道曲调，但不知道歌词。
glimpse	/ɡlɪmps/	n. 一瞥	NCE2 Lesson 42	I caught a glimpse of her on the bus.	我在公交车上瞥见了她。
snake	/sneɪk/	n. 蛇	NCE2 Lesson 42	Is that a snake in the grass?	草丛里那是一条蛇吗？
movement	/ˈmuːvmənt/	n. 动作	NCE2 Lesson 42	I noticed a movement behind the curtain.	我注意到窗帘后面动了一下。
continue	/kənˈtɪnjuː/	v. 继续	NCE2 Lesson 42	Shall we continue after lunch?	我们午饭后继续好吗？
dance	/dɑːns/	v. 跳舞	NCE2 Lesson 42	Would you like to dance?	你想跳舞吗？
obviously	/ˈɒbviəsli/	adv. 显然	NCE2 Lesson 42	He's obviously forgotten our meeting.	他显然忘了我们的会面。
difference	/ˈdɪfrəns/	n. 差别	NCE2 Lesson 42	What's the difference between these two?	这两个有什么区别？
Indian	/ˈɪndiən/	adj. 印度的	NCE2 Lesson 42	There's a good Indian restaurant near here.	这附近有一家不错的印度餐厅。
pole	/pəʊl/	n. （地球的）极	NCE2 Lesson 43	Have you ever wanted to visit the North Pole?	你有没有想过去北极？
flight	/flaɪt/	n. 飞行	NCE2 Lesson 43	How was your flight?	你这趟飞行还顺利吗？
explorer	/ɪkˈsplɔːrə/	n. 探险家	NCE2 Lesson 43	The explorer spent months in the mountains.	那位探险家在山里待了几个月。
lie	/laɪ/	v. 处于	NCE2 Lesson 43	The villages lie on opposite sides of the river.	这两个村庄位于河的两岸。
serious	/ˈsɪəriəs/	adj. 严重的	NCE2 Lesson 43	Is the damage serious?	损坏严重吗？
point	/pɔɪnt/	n. 地点	NCE2 Lesson 43	Let's meet at the same point tomorrow.	我们明天在同一个地点见吧。
seem	/siːm/	v. 似乎	NCE2 Lesson 43	You seem much happier today.	你今天看起来开心多了。
crash	/kræʃ/	v. 坠毁	NCE2 Lesson 43	Did the plane crash into the sea?	那架飞机坠入海里了吗？
sack	/sæk/	n. 袋子	NCE2 Lesson 43	Could you carry this sack of potatoes?	你能搬一下这袋土豆吗？
clear	/klɪə(r)/	v. 越过；adj. 无罪的，不亏心的	NCE2 Lesson 43, NCE2 Lesson 45	Do you think the horse can clear that fence?	你觉得那匹马能跳过那道栅栏吗？
aircraft	/ˈeəkrɑːft/	n. 飞机	NCE2 Lesson 43	How many people can this aircraft carry?	这架飞机能载多少人？
endless	/ˈendləs/	adj. 无尽的	NCE2 Lesson 43	The paperwork seems endless.	这些文书工作好像永远做不完。
plain	/pleɪn/	n. 平原	NCE2 Lesson 43	The town sits on a wide plain.	这个镇子位于一片广阔的平原上。
forest	/ˈfɒrɪst/	n. 森林	NCE2 Lesson 44	Let's walk through the forest.	我们穿过森林走走吧。
risk	/rɪsk/	n. 危险，冒险	NCE2 Lesson 44	I don't want to take that risk.	我不想冒那个险。
picnic	/ˈpɪknɪk/	n. 野餐	NCE2 Lesson 44	Shall we have a picnic by the river?	我们在河边野餐好吗？
edge	/edʒ/	n. 边缘	NCE2 Lesson 44	Keep your glass away from the edge.	把杯子放得离边缘远一点。
strap	/stræp/	n. 带，皮带	NCE2 Lesson 44	The strap on my bag has broken.	我的包带断了。
possession	/pəˈzeʃ(ə)n/	n. 所有物，财物；拥有	NCE2 Lesson 44	This ring is my most treasured possession.	这枚戒指是我最珍爱的物品。
breath	/breθ/	n. 呼吸	NCE2 Lesson 44	Let me catch my breath.	让我喘口气。
contents	/ˈkɒntents/	n. （常用复数）内有的物品	NCE2 Lesson 44	Please check the contents before signing.	签字前请检查里面的物品。
mend	/mend/	v. 修理	NCE2 Lesson 44	Can you mend this tear in my jacket?	你能补好我夹克上的这个口子吗？
conscience	/ˈkɒnʃəns/	n. 良心，道德心	NCE2 Lesson 45	I had a guilty conscience about lying to her.	我对她撒了谎，心里很内疚。
wallet	/ˈwɒlɪt/	n. 皮夹，钱夹	NCE2 Lesson 45	I think I've left my wallet at home.	我好像把钱包落在家里了。
savings	/ˈseɪvɪŋz/	n. 存款	NCE2 Lesson 45	We spent our savings on a new kitchen.	我们用积蓄装修了新厨房。
villager	/ˈvɪlɪdʒə(r)/	n. 村民	NCE2 Lesson 45	A villager showed us the way.	一位村民给我们指了路。
per cent	/pə ˈsent/	adv. 每一百，百分之……	NCE2 Lesson 45	The rent has gone up by ten per cent.	房租涨了百分之十。
unload	/ˌʌnˈləʊd/	v. 卸（货）	NCE2 Lesson 46	Can you help me unload the van?	你能帮我卸货车上的东西吗？
extremely	/ɪkˈstriːmli/	adv. 非常，极其	NCE2 Lesson 46	The roads are extremely busy today.	今天路上的车特别多。
occur	/əˈkɜː(r)/	v. 发生	NCE2 Lesson 46	When did the problem first occur?	这个问题最早是什么时候出现的？
astonish	/əˈstɒnɪʃ/	v. 使惊讶	NCE2 Lesson 46	Her energy never fails to astonish me.	她的精力总是让我惊叹。
pile	/paɪl/	n. 堆	NCE2 Lesson 46	Put those clothes in a pile.	把那些衣服堆在一起。
woollen	/ˈwʊlən/	adj. 羊毛的，毛纺的	NCE2 Lesson 46	You should bring a woollen jumper.	你应该带一件羊毛套衫。
goods	/ɡʊdz/	n. （常用复数）货物，商品	NCE2 Lesson 46	These goods were damaged in transit.	这些货物在运输中损坏了。
discover	/dɪˈskʌvə(r)/	v. 发现	NCE2 Lesson 46	How did you discover this café?	你是怎么发现这家咖啡馆的？
admit	/ədˈmɪt/	v. 承认	NCE2 Lesson 46	I admit I made a mistake.	我承认我犯了一个错误。
confine	/kənˈfaɪn/	v. 关在（一个狭小的空间里）	NCE2 Lesson 46	It's cruel to confine a dog to a tiny cage.	把狗关在小笼子里很残忍。
normal	/ˈnɔːm(ə)l/	adj. 正常的，通常的	NCE2 Lesson 46	Is that noise normal?	那种声音正常吗？
thirsty	/ˈθɜːsti/	adj. 口渴的；渴望的（课文标题含贪杯双关）	NCE2 Lesson 47	I'm thirsty. Could I have some water?	我口渴了，能给我一些水吗？
ghost	/ɡəʊst/	n. 鬼魂	NCE2 Lesson 47	Did you really see a ghost?	你真的看到鬼了吗？
haunt	/hɔːnt/	v. （鬼）来访，闹鬼	NCE2 Lesson 47	People say ghosts haunt that old house.	人们说那栋老房子闹鬼。
furniture	/ˈfɜːnɪtʃə(r)/	n. 家具	NCE2 Lesson 47	The flat comes with furniture.	这套公寓配有家具。
whisky	/ˈwɪski/	n. 威士忌酒	NCE2 Lesson 47	Would you like some whisky?	你想喝点威士忌吗？
suggest	/səˈdʒest/	v. 暗示；v. 提醒	NCE2 Lesson 47, NCE2 Lesson 87	Are you trying to suggest it was my fault?	你是在暗示那是我的错吗？
shake	/ʃeɪk/	v. 摇动	NCE2 Lesson 47	Please shake the bottle before opening it.	打开之前请摇一摇瓶子。
accept	/əkˈsept/	v. 接受	NCE2 Lesson 47	Do you accept card payments?	你们接受刷卡吗？
pull	/pʊl/	v. 拔	NCE2 Lesson 48	They had to pull the old tooth out.	他们不得不拔掉那颗坏牙。
cotton wool	/ˌkɒtn ˈwʊl/	n. 药棉	NCE2 Lesson 48	Have you got any cotton wool?	你有药棉吗？
collect	/kəˈlekt/	v. 搜集	NCE2 Lesson 48	Do you still collect stamps?	你还集邮吗？
collection	/kəˈlekʃ(ə)n/	n. 收藏品，收集品	NCE2 Lesson 48	You've got a lovely collection of postcards.	你收藏的这些明信片真漂亮。
nod	/nɒd/	v. 点头	NCE2 Lesson 48	Just nod if you agree.	如果你同意，点点头就行。
meanwhile	/ˈmiːnwaɪl/	adv. 同时	NCE2 Lesson 48	I'll cook dinner. Meanwhile, could you set the table?	我来做饭，这会儿你能摆好餐具吗？
tired	/ˈtaɪəd/	adj. 厌烦的	NCE2 Lesson 49	I'm tired of waiting for this bus.	等这辆公交车等得我烦了。
real	/ˈriːəl/	adj. 真正的	NCE2 Lesson 49	Is that a real diamond?	那是真钻石吗？
owner	/ˈəʊnə(r)/	n. 主人	NCE2 Lesson 49	Do you know the owner of this dog?	你认识这只狗的主人吗？
spring	/sprɪŋ/	n. 弹簧	NCE2 Lesson 49	There's a broken spring in this chair.	这把椅子里有根弹簧坏了。
mattress	/ˈmætrəs/	n. 床垫	NCE2 Lesson 49	This mattress is too soft for me.	这个床垫对我来说太软了。
gust	/ɡʌst/	n. 一阵风	NCE2 Lesson 49	A sudden gust blew my hat away.	一阵突如其来的风吹走了我的帽子。
sweep	/swiːp/	v. 扫，刮	NCE2 Lesson 49	Could you sweep the kitchen floor?	你能扫一下厨房地板吗？
courtyard	/ˈkɔːtjɑːd/	n. 院子	NCE2 Lesson 49	We had breakfast in the courtyard.	我们在院子里吃了早餐。
smash	/smæʃ/	v. 碰碎，摔碎	NCE2 Lesson 49	Be careful not to smash that vase.	小心别把那个花瓶摔碎了。
miraculously	/mɪˈrækjələsli/	adv. 奇迹般地	NCE2 Lesson 49	Miraculously, nobody was hurt.	奇迹般地，没有人受伤。
unhurt	/ʌnˈhɜːt/	adj. 没有受伤的	NCE2 Lesson 49	Luckily, everyone was unhurt.	幸运的是，大家都没受伤。
glance	/ɡlɑːns/	v. 扫视	NCE2 Lesson 49	Could you glance at this email before I send it?	我发这封邮件之前，你能帮我看一眼吗？
promptly	/ˈprɒmptli/	adv. 迅速地	NCE2 Lesson 49	She answered my email promptly.	她很快就回复了我的邮件。
ride	/raɪd/	n. 旅行	NCE2 Lesson 50	Thanks for the ride home.	谢谢你开车送我回家。
excursion	/ɪkˈskɜːʃn/	n. 远足	NCE2 Lesson 50	We went on an excursion to a nearby island.	我们去附近的一座小岛游玩了一趟。
conductor	/kənˈdʌktə(r)/	n. 列车员，售票员	NCE2 Lesson 50	The conductor came round to check our tickets.	列车员过来检查了我们的票。
view	/vjuː/	n. 景色	NCE2 Lesson 50	The view from this window is amazing.	这扇窗外的风景太美了。
reward	/rɪˈwɔːd/	n. 报偿 v. 给奖赏	NCE2 Lesson 51	There's a reward for finding the missing dog.	找到走失的狗会有酬谢。
virtue	/ˈvɜːtʃuː/	n. 美德	NCE2 Lesson 51	Patience is a virtue, especially with children.	耐心是一种美德，对待孩子尤其如此。
diet	/ˈdaɪət/	n. 节食	NCE2 Lesson 51	I'm trying to stick to my diet.	我在努力坚持节食。
forbid	/fəˈbɪd/	v. 禁止	NCE2 Lesson 51	The rules forbid smoking inside.	规定禁止在室内吸烟。
hurriedly	/ˈhʌrɪdli/	adv. 匆忙地	NCE2 Lesson 51	He hurriedly packed his bag and left.	他匆忙收拾好包就走了。
embarrass	/ɪmˈbærəs/	v. 使尴尬	NCE2 Lesson 51	Please don't embarrass me in front of everyone.	请别让我在大家面前难堪。
guiltily	/ˈɡɪltɪli/	adv. 内疚地	NCE2 Lesson 51	She smiled guiltily at the empty cake tin.	她看着空蛋糕盒，内疚地笑了笑。
strict	/strɪkt/	adj. 严格的	NCE2 Lesson 51	My old school was very strict.	我以前的学校管得很严。
occasionally	/əˈkeɪʒnəli/	adv. 偶尔地	NCE2 Lesson 51	We meet for coffee occasionally.	我们偶尔约着喝咖啡。
temporarily	/ˈtemprərəli/	adv. 暂时地	NCE2 Lesson 52	The road is temporarily closed.	这条路暂时封闭了。
inch	/ɪntʃ/	n. 英寸（度量单位）	NCE2 Lesson 52	Move it an inch to the left.	把它往左移一英寸。
space	/speɪs/	n. 空间	NCE2 Lesson 52, NCE2 Lesson 61	Is there enough space for another chair?	还有地方再放一把椅子吗？
actually	/ˈæktʃuəli/	adv. 实际上	NCE2 Lesson 52	I actually quite enjoyed the film.	其实我挺喜欢那部电影的。
hot	/hɒt/	adj. 带电的（电学用法，英式英语也常用 live）	NCE2 Lesson 53	The electrician said the wire was still hot.	电工说那根电线还带着电。
fireman	/ˈfaɪəmən/	n. 消防队员	NCE2 Lesson 53	A fireman helped us out of the building.	一名消防员帮助我们撤出了大楼。
        """.trimIndent(),
        """
cause	/kɔːz/	v. 引起 n. 原因	NCE2 Lesson 53	Too much noise can cause stress.	过多的噪声会引起压力。
examine	/ɪɡˈzæmɪn/	v. 检查	NCE2 Lesson 53	The mechanic needs to examine the engine.	修理工需要检查发动机。
accidentally	/ˌæksɪˈdentəli/	adv. 意外地，偶然地	NCE2 Lesson 53	I accidentally deleted your message.	我不小心删掉了你的消息。
remains	/rɪˈmeɪnz/	n. 尸体，残骸	NCE2 Lesson 53	They found the remains of an old boat.	他们发现了一艘旧船的残骸。
wire	/ˈwaɪə(r)/	n. 电线	NCE2 Lesson 53	That wire looks damaged.	那根电线看起来损坏了。
volt	/vəʊlt/	n. 伏特（电压单位）	NCE2 Lesson 53	Is the voltage less than one volt?	电压不到一伏吗？
power line	/ˈpaʊə laɪn/	n. 电力线	NCE2 Lesson 53	A tree fell onto a power line.	一棵树倒在了电力线上。
solve	/sɒlv/	v. 解决	NCE2 Lesson 53	Did you manage to solve the problem?	你把问题解决了吗？
mystery	/ˈmɪst(ə)ri/	n. 谜，难以解释的事	NCE2 Lesson 53	Where my keys went is a complete mystery.	我的钥匙去哪儿了，完全是个谜。
snatch	/snætʃ/	v. 一把抓住；抢走	NCE2 Lesson 53	I saw someone snatch her bag.	我看见有人抢走了她的包。
spark	/spɑːk/	n. 电火花	NCE2 Lesson 53	I saw a spark near the plug.	我看到插头附近冒了一下火花。
sticky	/ˈstɪki/	adj. 粘的	NCE2 Lesson 54	Why is the table so sticky?	桌子怎么这么黏？
finger	/ˈfɪŋɡə(r)/	n. 手指	NCE2 Lesson 54	I've cut my finger.	我割伤了手指。
pie	/paɪ/	n. 馅饼	NCE2 Lesson 54	Would you like a slice of apple pie?	你想吃一块苹果派吗？
mix	/mɪks/	v. 混合，拌和	NCE2 Lesson 54	Mix the flour and water together.	把面粉和水混合在一起。
pastry	/ˈpeɪstri/	n. 油酥面团，酥皮；酥皮糕点	NCE2 Lesson 54	Did you make the pastry yourself?	这酥皮是你自己做的吗？
annoying	/əˈnɔɪɪŋ/	adj. 恼人的	NCE2 Lesson 54	That buzzing noise is really annoying.	那嗡嗡声真烦人。
receiver	/rɪˈsiːvə(r)/	n. 电话听筒	NCE2 Lesson 54	He put down the receiver without saying goodbye.	他没说再见就放下了电话听筒。
dismay	/dɪsˈmeɪ/	n. 沮丧，惊慌；v. 使沮丧	NCE2 Lesson 54, NCE2 Lesson 86	To my dismay, the last train had already left.	令我沮丧的是，末班火车已经走了。
recognize	/ˈrekəɡnaɪz/	v. 认出，听出	NCE2 Lesson 54	I didn't recognize you with your new haircut.	你换了发型，我都没认出来。
persuade	/pəˈsweɪd/	v. 说服，劝说	NCE2 Lesson 54	Can you persuade him to come along?	你能说服他一起来吗？
mess	/mes/	n. 乱七八糟	NCE2 Lesson 54	Sorry about the mess in here.	抱歉，这里有点乱。
doorknob	/ˈdɔːnɒb/	n. 门把手	NCE2 Lesson 54	The doorknob has come loose.	门把手松了。
register	/ˈredʒɪstə(r)/	v. 挂号邮寄	NCE2 Lesson 54	Can I register this letter at the counter?	我能在柜台把这封信按挂号信寄出吗？
gold	/ɡəʊld/	n. 金子	NCE2 Lesson 55	Is this ring made of gold?	这枚戒指是金的吗？
mine	/maɪn/	n. 矿	NCE2 Lesson 55	My grandfather worked in a coal mine.	我爷爷曾在煤矿工作。
treasure	/ˈtreʒə(r)/	n. 财宝	NCE2 Lesson 55	The children are pretending to look for buried treasure.	孩子们正假装寻找埋藏的宝藏。
revealer	/rɪˈviːlə(r)/	n. 揭示者（课文中 treasure revealer 指探宝仪）	NCE2 Lesson 55	The story calls the machine a treasure revealer.	故事里把那台机器称为宝藏探测器。
invent	/ɪnˈvent/	v. 发明	NCE2 Lesson 55	Who helped invent the first computer?	谁参与发明了第一台计算机？
detect	/dɪˈtekt/	v. 探测	NCE2 Lesson 55	This alarm can detect smoke.	这个报警器能探测烟雾。
bury	/ˈberi/	v. 埋藏	NCE2 Lesson 55	The dog tried to bury its toy.	那只狗想把玩具埋起来。
cave	/keɪv/	n. 山洞	NCE2 Lesson 55	We explored a cave near the beach.	我们探索了海滩附近的一个山洞。
seashore	/ˈsiːʃɔː(r)/	n. 海岸	NCE2 Lesson 55	We collected shells on the seashore.	我们在海边捡了贝壳。
pirate	/ˈpaɪrət/	n. 海盗	NCE2 Lesson 55	He's dressed as a pirate for the party.	他为聚会打扮成了海盗。
arm	/ɑːm/	v. 武装	NCE2 Lesson 55	The game lets you arm your character with a sword.	这款游戏允许你给角色装备一把剑。
soil	/sɔɪl/	n. 泥土	NCE2 Lesson 55	The soil is still wet from yesterday's rain.	昨天的雨让泥土现在还湿着。
entrance	/ˈentrəns/	n. 入口	NCE2 Lesson 55	Where's the entrance to the car park?	停车场的入口在哪里？
finally	/ˈfaɪnəli/	adv. 最后	NCE2 Lesson 55	I've finally finished the paperwork.	我终于把文书工作做完了。
worthless	/ˈwɜːθləs/	adj. 毫无价值的	NCE2 Lesson 55	The tickets are worthless now that the concert's cancelled.	演唱会取消了，这些票现在没有价值了。
thoroughly	/ˈθʌrəli/	adv. 彻底地	NCE2 Lesson 55	Wash the vegetables thoroughly.	把蔬菜洗干净。
trunk	/trʌŋk/	n. 行李箱；n. 树干	NCE2 Lesson 55, NCE2 Lesson 58	There's an old trunk in the attic.	阁楼里有一个旧衣箱。
confident	/ˈkɒnfɪdənt/	adj. 有信心的	NCE2 Lesson 55	I feel more confident speaking English now.	我现在说英语更有信心了。
value	/ˈvæljuː/	n. 价值	NCE2 Lesson 55	Do you know the value of this watch?	你知道这块手表值多少钱吗？
sound	/saʊnd/	n. 声音	NCE2 Lesson 56	What's that strange sound?	那奇怪的声音是什么？
excitement	/ɪkˈsaɪtmənt/	n. 激动，兴奋	NCE2 Lesson 56	The children couldn't sleep because of the excitement.	孩子们太兴奋，睡不着。
handsome	/ˈhænsəm/	adj. 漂亮的；美观的	NCE2 Lesson 56	That's a handsome old building.	那是一栋漂亮的老建筑。
Rolls-Royce	/ˌrəʊlz ˈrɔɪs/	n. 罗尔斯--罗伊斯	NCE2 Lesson 56	We hired a Rolls-Royce for the wedding.	我们为婚礼租了一辆劳斯莱斯。
Benz	/benz/	n. 奔驰	NCE2 Lesson 56	My uncle drives an old Mercedes-Benz.	我叔叔开一辆旧奔驰。
wheel	/wiːl/	n. 轮子	NCE2 Lesson 56	The front wheel is loose.	前轮松了。
explosion	/ɪkˈspləʊʒ(ə)n/	n. 爆炸，轰响	NCE2 Lesson 56	We heard a loud explosion in the distance.	我们听到远处传来巨大的爆炸声。
course	/kɔːs/	n. 跑道；行程	NCE2 Lesson 56	The runners are already on the course.	跑步选手们已经在赛道上了。
rival	/ˈraɪv(ə)l/	n. 对手	NCE2 Lesson 56	Our biggest rival has opened another shop.	我们最大的竞争对手又开了一家店。
speed	/spiːd/	v. 疾驶	NCE2 Lesson 56	Please don't speed through the village.	请不要在村庄里超速行驶。
downhill	/ˌdaʊnˈhɪl/	adv. 下坡	NCE2 Lesson 56	It's easier going downhill.	下坡走起来更轻松。
madam	/ˈmædəm/	n. （对妇女的尊称）太太，夫人	NCE2 Lesson 57	Can I help you, madam?	夫人，有什么可以帮您的吗？
jeans	/dʒiːnz/	n. 牛仔裤	NCE2 Lesson 57	Can I wear jeans to the interview?	我能穿牛仔裤去面试吗？
hesitate	/ˈhezɪteɪt/	v. 犹豫，迟缓	NCE2 Lesson 57	Don't hesitate to ask for help.	需要帮助就尽管说。
serve	/sɜːv/	v. 接待（顾客）	NCE2 Lesson 57	Are you waiting for someone to serve you?	你是在等店员接待吗？
scornfully	/ˈskɔːnfəli/	adv. 轻蔑地	NCE2 Lesson 57	He laughed scornfully at my suggestion.	他对我的建议轻蔑地笑了笑。
punish	/ˈpʌnɪʃ/	v. 惩罚	NCE2 Lesson 57	It isn't fair to punish everyone.	惩罚所有人是不公平的。
fur	/fɜː(r)/	n. 裘皮	NCE2 Lesson 57	Is that real fur or fake fur?	那是真皮草还是人造皮草？
eager	/ˈiːɡə(r)/	adj. 热切的，热情的	NCE2 Lesson 57	I'm eager to hear your news.	我迫切地想听听你的消息。
blessing	/ˈblesɪŋ/	n. 福分，福气	NCE2 Lesson 58	Having family nearby is a real blessing.	家人住在附近真是一种福气。
disguise	/dɪsˈɡaɪz/	n. 伪装	NCE2 Lesson 58	I almost didn't recognize him in that disguise.	他那副伪装让我差点没认出他。
tiny	/ˈtaɪni/	adj. 极小的	NCE2 Lesson 58	The kitchen is tiny, but it works for us.	厨房很小，不过够我们用。
possess	/pəˈzes/	v. 拥有	NCE2 Lesson 58	Do you possess a valid driving licence?	你持有有效驾驶执照吗？
cursed	/ˈkɜːsɪd/	adj. 可恶的，可恨的	NCE2 Lesson 58	This cursed printer has stopped again!	这该死的打印机又停了！
increase	/ɪnˈkriːs/	v. 增加	NCE2 Lesson 58	Will they increase the rent next year?	他们明年会涨房租吗？
plant	/plɑːnt/	v. 种植；v. 安放	NCE2 Lesson 58, NCE2 Lesson 79	Let's plant some herbs by the window.	我们在窗边种些香草吧。
church	/tʃɜːtʃ/	n. 教堂	NCE2 Lesson 58	The church bells wake me up on Sundays.	星期天，教堂的钟声会把我叫醒。
evil	/ˈiːv(ə)l/	adj. 坏的	NCE2 Lesson 58	The villain has an evil laugh.	那个反派的笑声很邪恶。
reputation	/ˌrepjuˈteɪʃ(ə)n/	n. 名声	NCE2 Lesson 58	That garage has a good reputation.	那家修车厂口碑很好。
claim	/kleɪm/	v. 声称；夺去（生命）	NCE2 Lesson 58, NCE2 Lesson 82	Did he really claim to have seen a ghost?	他真说自己见过鬼吗？
victim	/ˈvɪktɪm/	n. 受害者，牺牲品	NCE2 Lesson 58	She was the victim of an online scam.	她是一起网络诈骗的受害者。
vicar	/ˈvɪkə(r)/	n. 教区牧师	NCE2 Lesson 58	The vicar lives next to the church.	牧师住在教堂旁边。
source	/sɔːs/	n. 来源	NCE2 Lesson 58	What's the source of that information?	那条信息的来源是什么？
income	/ˈɪnkʌm/	n. 收入	NCE2 Lesson 58	My income changes from month to month.	我的收入每个月都不一样。
gain	/ɡeɪn/	v. 受益	NCE2 Lesson 58	You'll gain a lot from this course.	你会从这门课程中获益很多。
bark	/bɑːk/	v. 狗叫	NCE2 Lesson 59	Does your dog bark at strangers?	你的狗会冲着陌生人叫吗？
press	/pres/	v. 按，压；n. 新闻界	NCE2 Lesson 59, NCE2 Lesson 84	Press this button to open the door.	按这个按钮开门。
paw	/pɔː/	n. 脚爪	NCE2 Lesson 59	The dog has hurt its front paw.	那只狗的前爪受伤了。
latch	/lætʃ/	n. 门闩	NCE2 Lesson 59	The latch on the gate is broken.	院门上的门闩坏了。
expert	/ˈekspɜːt/	n. 专家	NCE2 Lesson 59	I'm no expert, but that doesn't look right.	我不是专家，但那看起来不太对。
develop	/dɪˈveləp/	v. 养成	NCE2 Lesson 59	I'm trying to develop better study habits.	我在努力养成更好的学习习惯。
habit	/ˈhæbɪt/	n. 习惯	NCE2 Lesson 59	I've got into the habit of walking after dinner.	我已经养成了晚饭后散步的习惯。
remove	/rɪˈmuːv/	v. 拆掉，取下	NCE2 Lesson 59	Please remove your shoes at the door.	请在门口脱鞋。
future	/ˈfjuːtʃə(r)/	n. 未来，前途	NCE2 Lesson 60	What would you like to do in the future?	你将来想做什么？
fair	/feə(r)/	n. 集市	NCE2 Lesson 60	Are you going to the village fair?	你要去村里的集市吗？
fortune-teller	/ˈfɔːtʃuːn telə(r)/	n. 算命人	NCE2 Lesson 60	Have you ever visited a fortune-teller?	你找人算过命吗？
crystal	/ˈkrɪst(ə)l/	n. 水晶	NCE2 Lesson 60	Is that bowl made of crystal?	那个碗是水晶做的吗？
relation	/rɪˈleɪʃ(ə)n/	n. 亲属	NCE2 Lesson 60	Is he a relation of yours?	他是你的亲戚吗？
impatiently	/ɪmˈpeɪʃntli/	adv. 不耐烦地	NCE2 Lesson 60	He tapped his foot impatiently.	他不耐烦地用脚敲着地面。
Hubble	/ˈhʌb(ə)l/	n. 哈勃	NCE2 Lesson 61	Have you seen those photos from Hubble?	你看过哈勃望远镜拍的那些照片吗？
telescope	/ˈtelɪskəʊp/	n. 望远镜	NCE2 Lesson 61	You can see the moon through this telescope.	通过这架望远镜，你可以看到月球。
launch	/lɔːntʃ/	v. 发射	NCE2 Lesson 61	When will they launch the rocket?	他们什么时候发射火箭？
NASA	/ˈnæsə/	n. (National Aeronautics and Space Administration) 国家航空和航天局	NCE2 Lesson 61	I found the photo on the NASA website.	我在美国航空航天局的网站上找到了这张照片。
billion	/ˈbɪljən/	n. 10 亿	NCE2 Lesson 61	The project will cost a billion dollars.	这个项目将耗资十亿美元。
faulty	/ˈfɔːlti/	adj. 有错误的	NCE2 Lesson 61	I think this charger is faulty.	我觉得这个充电器有故障。
astronaut	/ˈæstrənɔːt/	n. 宇航员	NCE2 Lesson 61	She wanted to be an astronaut as a child.	她小时候想当宇航员。
shuttle	/ˈʃʌt(ə)l/	n. 航天飞机	NCE2 Lesson 61	We saw a space shuttle at the museum.	我们在博物馆看到了航天飞机。
        """.trimIndent(),
        """
Endeavour	/ɪnˈdevə(r)/	n. 奋进号（航天飞机名）；endeavour 也指努力	NCE2 Lesson 61	Endeavour was the name of a space shuttle.	奋进号是一架航天飞机的名字。
robot-arm	/ˈrəʊbɒt ɑːm/	n. 机械臂（常写作 robot arm）	NCE2 Lesson 61	That robot-arm can pick up a cup.	那个机械臂能拿起杯子。
grab	/ɡræb/	v. 抓	NCE2 Lesson 61	I'll grab my coat and meet you outside.	我拿上外套就去外面找你。
atmosphere	/ˈætməsfɪə(r)/	n. 大气层	NCE2 Lesson 61	The rocket passed through the atmosphere.	火箭穿过了大气层。
distant	/ˈdɪstənt/	adj. 遥远的	NCE2 Lesson 61	We could see distant mountains from the train.	我们从火车上能看到远处的山。
galaxy	/ˈɡæləksi/	n. 星系	NCE2 Lesson 61	Our galaxy contains billions of stars.	我们所在的星系有数十亿颗恒星。
universe	/ˈjuːnɪvɜːs/	n. 宇宙	NCE2 Lesson 61	How big is the universe?	宇宙有多大？
eagle eye	/ˌiːɡl ˈaɪ/	n. 敏锐的目光；鹰眼	NCE2 Lesson 61	Keep an eagle eye on your bag.	仔细看好你的包。
control	/kənˈtrəʊl/	n. 控制	NCE2 Lesson 62	Who's in control of the budget?	谁负责管理预算？
smoke	/sməʊk/	n. 烟	NCE2 Lesson 62	I can smell smoke.	我闻到烟味了。
desolate	/ˈdesələt/	adj. 荒凉的	NCE2 Lesson 62	The beach looked desolate in winter.	冬天的海滩看起来很荒凉。
threaten	/ˈθret(ə)n/	v. 威胁	NCE2 Lesson 62	Don't threaten to leave every time we disagree.	别每次我们意见不合就威胁要离开。
surrounding	/səˈraʊndɪŋ/	adj. 周围的	NCE2 Lesson 62	We spent a day exploring the surrounding area.	我们花了一天逛周边地区。
destruction	/dɪˈstrʌkʃ(ə)n/	n. 破坏，毁灭	NCE2 Lesson 62	The storm caused widespread destruction.	暴风雨造成了大范围的破坏。
flood	/flʌd/	n. 洪水，水灾	NCE2 Lesson 62	The shop was damaged in the flood.	那家商店在洪水中受损了。
authority	/ɔːˈθɒrəti/	n. （常用复数）当局	NCE2 Lesson 62	Report the problem to the local authority.	向地方主管部门报告这个问题。
grass-seed	/ˈɡrɑːs siːd/	n. 草籽（常写作 grass seed）	NCE2 Lesson 62	We need some grass-seed for the lawn.	我们的草坪需要一些草籽。
spray	/spreɪ/	v. 喷撒	NCE2 Lesson 62	Don't spray water near the sockets.	别往插座附近喷水。
quantity	/ˈkwɒntəti/	n. 量	NCE2 Lesson 62	What quantity would you like to order?	你想订多少？
root	/ruːt/	n. 根	NCE2 Lesson 62	A tree root has cracked the pavement.	一条树根把人行道顶裂了。
century	/ˈsentʃəri/	n. 世纪	NCE2 Lesson 62	This house was built in the last century.	这栋房子建于上个世纪。
patch	/pætʃ/	n. 小片	NCE2 Lesson 62	There's a wet patch on the ceiling.	天花板上有一块水渍。
blacken	/ˈblækən/	v. 变黑，发暗	NCE2 Lesson 62	Smoke can blacken the walls.	烟会把墙壁熏黑。
circle	/ˈsɜːk(ə)l/	n. 圈子	NCE2 Lesson 63	We've got a small circle of close friends.	我们有一个小小的密友圈。
admire	/ədˈmaɪə(r)/	v. 赞美，钦佩	NCE2 Lesson 63	I really admire your patience.	我真佩服你的耐心。
close	/kləʊs/	adj. 亲密的	NCE2 Lesson 63	We're still close friends.	我们仍然是亲密的朋友。
wedding	/ˈwedɪŋ/	n. 婚礼	NCE2 Lesson 63	Are you going to Emma's wedding?	你要去参加艾玛的婚礼吗？
reception	/rɪˈsepʃ(ə)n/	n. 招待会	NCE2 Lesson 63	The wedding reception is at a nearby hotel.	婚宴在附近的一家酒店举行。
sort	/sɔːt/	n. 种类	NCE2 Lesson 63	What sort of music do you like?	你喜欢哪种音乐？
tunnel	/ˈtʌn(ə)l/	n. 隧道	NCE2 Lesson 64	The train goes through a long tunnel.	火车要穿过一条长隧道。
port	/pɔːt/	n. 港口	NCE2 Lesson 64	The ship is due in port tomorrow.	那艘船预计明天抵港。
ventilate	/ˈventɪleɪt/	v. 通风	NCE2 Lesson 64	Open the windows to ventilate the room.	打开窗户，给房间通通风。
chimney	/ˈtʃɪmni/	n. 烟囱	NCE2 Lesson 64	There's a bird on the chimney.	烟囱上有一只鸟。
sea level	/ˈsiː lev(ə)l/	n. 海平面	NCE2 Lesson 64	How high are we above sea level?	我们现在海拔多高？
double	/ˈdʌb(ə)l/	adj. 双的	NCE2 Lesson 64	Could we have a room with a double bed?	能给我们一间带双人床的房间吗？
ventilation	/ˌventɪˈleɪʃn/	n. 通风	NCE2 Lesson 64	This room needs better ventilation.	这个房间需要改善通风。
fear	/fɪə(r)/	v. 害怕，担心；恐怕	NCE2 Lesson 64	I fear we've missed the last bus.	恐怕我们错过末班公交车了。
invasion	/ɪnˈveɪʒ(ə)n/	n. 入侵，侵略	NCE2 Lesson 64	The museum has an exhibition about the invasion.	博物馆里有关于那次入侵的展览。
officially	/əˈfɪʃəli/	adv. 正式地	NCE2 Lesson 64	The new library officially opens on Monday.	新图书馆星期一正式开放。
connect	/kəˈnekt/	v. 连接	NCE2 Lesson 64	How do I connect to the Wi-Fi?	我怎么连接无线网络？
European	/ˌjʊərəˈpiːən/	adj. 欧洲的	NCE2 Lesson 64	Have you visited any European countries?	你去过哪些欧洲国家吗？
continent	/ˈkɒntɪnənt/	n. 大陆	NCE2 Lesson 64	Which continent is that country in?	那个国家在哪个洲？
versus	/ˈvɜːsəs/	prep. 对，对抗（常缩写为 vs）	NCE2 Lesson 65	Are you watching England versus France tonight?	你今晚看英格兰对法国的比赛吗？
Christmas	/ˈkrɪsməs/	n. 圣诞节	NCE2 Lesson 65	What are you doing for Christmas?	圣诞节你准备做什么？
circus	/ˈsɜːkəs/	n. 马戏团	NCE2 Lesson 65	I went to the circus as a child.	我小时候去看过马戏表演。
present	/ˈprezənt/（名词、形容词）；/prɪˈzent/（动词）	n. 礼物；adj. 目前的；v. 演出；adj. 出席，到场的；v. 赠送	NCE2 Lesson 65, NCE2 Lesson 76, NCE2 Lesson 89, NCE2 Lesson 93	I've bought a present for your mum.	我给你妈妈买了一份礼物。
accompany	/əˈkʌmpəni/	v. 陪伴, 随行	NCE2 Lesson 65	Can someone accompany her to the appointment?	有人能陪她去赴约吗？
approach	/əˈprəʊtʃ/	v. 走近	NCE2 Lesson 65	Please approach the dog slowly.	请慢慢靠近那只狗。
ought	/ɔːt/	v. 应该	NCE2 Lesson 65	We ought to leave soon.	我们应该快点出发了。
weigh	/weɪ/	v. 重	NCE2 Lesson 65	How much does your suitcase weigh?	你的行李箱有多重？
fortunate	/ˈfɔːtʃənət/	adj. 幸运的	NCE2 Lesson 65	We were fortunate to get the last two seats.	我们很幸运，买到了最后两个座位。
Lancaster	/ˈlæŋkəstə(r)/	n. 兰开斯特	NCE2 Lesson 66	Is that a Lancaster in the museum?	博物馆里的那架是兰开斯特轰炸机吗？
bomber	/ˈbɒmə(r)/	n. 轰炸机	NCE2 Lesson 66	My grandfather flew a bomber during the war.	我爷爷在战争期间驾驶过轰炸机。
remote	/rɪˈməʊt/	adj. 偏僻的	NCE2 Lesson 66	She works in a remote mountain village.	她在一个偏远的山村工作。
Pacific	/pəˈsɪfɪk/	n. 太平洋	NCE2 Lesson 66	I've never flown across the Pacific.	我从未飞越过太平洋。
wreck	/rek/	n. 残骸	NCE2 Lesson 66	Divers found the wreck near the island.	潜水员在岛屿附近发现了沉船残骸。
rediscover	/ˌriːdɪˈskʌvə(r)/	v. 重新发现	NCE2 Lesson 66	I'd love to rediscover my interest in painting.	我很想重新找回对绘画的兴趣。
aerial	/ˈeəriəl/	adj. 航空的	NCE2 Lesson 66	This aerial photo shows the whole town.	这张航拍照片展示了整个镇子。
survey	/ˈsɜːveɪ/	n. 调查	NCE2 Lesson 66	Have you filled in the customer survey?	你填写顾客调查问卷了吗？
rescue	/ˈreskjuː/	v. 营救（＝save）	NCE2 Lesson 66	Firefighters came to rescue the trapped cat.	消防员来营救那只被困的猫。
package	/ˈpækɪdʒ/	v. 把……打包	NCE2 Lesson 66	We need to package these glasses carefully.	我们得仔细包装这些玻璃杯。
enthusiast	/ɪnˈθjuːziæst/	n. 爱好者，热衷者	NCE2 Lesson 66	My brother is a real cycling enthusiast.	我哥哥是个十足的骑行爱好者。
restore	/rɪˈstɔː(r)/	v. 修复（修并且复原,如对艺术品的修复）	NCE2 Lesson 66	They're trying to restore the old theatre.	他们正设法修复那座老剧院。
imagine	/ɪˈmædʒɪn/	v. 想像	NCE2 Lesson 66	Can you imagine living without a phone?	你能想象没有手机的生活吗？
packing case	/ˈpækɪŋ keɪs/	n. 包装箱	NCE2 Lesson 66	The painting arrived in a wooden packing case.	那幅画装在一个木包装箱里送到了。
colony	/ˈkɒləni/	n. 群	NCE2 Lesson 66	There's a colony of bees in that tree.	那棵树里住着一群蜜蜂。
bee	/biː/	n. 蜂	NCE2 Lesson 66	A bee flew in through the window.	一只蜜蜂从窗户飞了进来。
hive	/haɪv/	n. 蜂房	NCE2 Lesson 66	Don't stand too close to the hive.	别站得离蜂箱太近。
preserve	/prɪˈzɜːv/	v. 保护	NCE2 Lesson 66	We want to preserve the old building.	我们想保留这栋老建筑。
beeswax	/ˈbiːzwæks/	n. 蜂蜡	NCE2 Lesson 66	This candle is made from beeswax.	这支蜡烛是蜂蜡做的。
volcano	/vɒlˈkeɪnəʊ/	n. 火山	NCE2 Lesson 67	Have you ever seen a volcano?	你见过火山吗？
active	/ˈæktɪv/	adj. 活动的	NCE2 Lesson 67	Is that volcano still active?	那座火山仍然活跃吗？
Kivu	/ˈkiːvuː/	n. 基伍湖	NCE2 Lesson 67	Can you find Lake Kivu on the map?	你能在地图上找到基伍湖吗？
Congo	/ˈkɒŋɡəʊ/	n. 刚果	NCE2 Lesson 67	Have you ever been to the Congo?	你去过刚果吗？
Kituro	/kɪˈtuːrəʊ/	n. 基图罗	NCE2 Lesson 67	The lesson describes an eruption of Kituro.	这一课描述了基图罗火山的一次喷发。
erupt	/ɪˈrʌpt/	v. （火山）喷发	NCE2 Lesson 67	Could this volcano erupt again?	这座火山会再次喷发吗？
violently	/ˈvaɪələntli/	adv. 猛烈地，剧烈地	NCE2 Lesson 67	The windows shook violently in the storm.	窗户在暴风雨中剧烈摇晃。
manage	/ˈmænɪdʒ/	v. 设法	NCE2 Lesson 67	Did you manage to find the keys?	你找到钥匙了吗？
brilliant	/ˈbrɪliənt/	adj. 精彩的	NCE2 Lesson 67	That was a brilliant performance.	那真是一场精彩的演出。
liquid	/ˈlɪkwɪd/	adj. 液态的；n. 液体	NCE2 Lesson 67	Do you use liquid soap?	你用液体洗手皂吗？
escape	/ɪˈskeɪp/	v. 逃脱	NCE2 Lesson 67	How did the dog escape from the garden?	那只狗是怎么从花园跑出去的？
alive	/əˈlaɪv/	adj. 活着的	NCE2 Lesson 67	Is that plant still alive?	那株植物还活着吗？
persistent	/pəˈsɪstənt/	adj. 坚持的，固执的	NCE2 Lesson 68	You have to be persistent when looking for work.	找工作时，你得坚持不懈。
avoid	/əˈvɔɪd/	v. 避开	NCE2 Lesson 68	Let's avoid the main road at rush hour.	高峰时段我们避开主干道吧。
insist	/ɪnˈsɪst/	v. 坚持做	NCE2 Lesson 68	If you insist, I'll stay for dinner.	如果你坚持，我就留下来吃晚饭。
murder	/ˈmɜːdə(r)/	n. 谋杀	NCE2 Lesson 69	The police are investigating a murder.	警方正在调查一起谋杀案。
instruct	/ɪnˈstrʌkt/	v. 命令，指示；v. 指导，传授	NCE2 Lesson 69, NCE2 Lesson 94	The coach will instruct us in the basic techniques.	教练会教我们基本技巧。
acquire	/əˈkwaɪə(r)/	v. 取得，获得	NCE2 Lesson 69	It takes time to acquire new skills.	掌握新技能需要时间。
confidence	/ˈkɒnfɪdəns/	n. 信心	NCE2 Lesson 69	Practice has given me more confidence.	练习让我更有信心了。
examiner	/ɪɡˈzæmɪnə(r)/	n. 主考人	NCE2 Lesson 69	The examiner asked me to turn left.	考官让我向左转。
suppose	/səˈpəʊz/	v. 假设	NCE2 Lesson 69	Suppose it rains. What shall we do?	假如下雨，我们怎么办？
tap	/tæp/	v. 轻敲	NCE2 Lesson 69	Just tap the screen once.	轻点一下屏幕就行。
react	/riˈækt/	v. 反应	NCE2 Lesson 69	How did she react to the news?	她听到消息后有什么反应？
brake	/breɪk/	n. 刹车	NCE2 Lesson 69	The mechanic checked the brake pads.	修理工检查了刹车片。
pedal	/ˈped(ə)l/	n. 踏板	NCE2 Lesson 69	My foot slipped off the pedal.	我的脚从踏板上滑了下来。
mournful	/ˈmɔːnf(ə)l/	adj. 悲哀的	NCE2 Lesson 69	The dog gave me a mournful look.	那只狗可怜巴巴地看了我一眼。
bullfight	/ˈbʊlfaɪt/	n. 斗牛	NCE2 Lesson 70	I've never been to a bullfight.	我从没去看过斗牛。
drunk	/drʌŋk/	n. 醉汉	NCE2 Lesson 70	A drunk was shouting outside the pub.	一个醉汉在酒吧外大喊大叫。
wander	/ˈwɒndə(r)/	v. 溜达，乱走	NCE2 Lesson 70	Let's wander round the old town.	我们在老城区随便逛逛吧。
unaware	/ˌʌnəˈweə(r)/	adj. 不知道的，未觉察的	NCE2 Lesson 70	I was unaware that the time had changed.	我不知道时间已经改了。
        """.trimIndent(),
        """
bull	/bʊl/	n. 公牛	NCE2 Lesson 70	There's a bull in that field.	那块田里有一头公牛。
matador	/ˈmætədɔː(r)/	n. 斗牛士	NCE2 Lesson 70	The matador stepped into the ring.	斗牛士走进了竞技场。
apparently	/əˈpærəntli/	adv. 据说；看来，显然	NCE2 Lesson 70	Apparently, the shop is closing next month.	听说那家店下个月要关门了。
sensitive	/ˈsensətɪv/	adj. 敏感的	NCE2 Lesson 70	He's quite sensitive about his age.	他对自己的年龄很敏感。
criticism	/ˈkrɪtɪsɪzəm/	n. 批评	NCE2 Lesson 70	Try not to take the criticism personally.	尽量不要觉得那些批评是在针对你个人。
charge	/tʃɑːdʒ/	v. 冲上去	NCE2 Lesson 70	We saw the bull charge towards the gate.	我们看到那头公牛冲向大门。
clumsily	/ˈklʌmzɪli/	adv. 笨拙地	NCE2 Lesson 70	I clumsily knocked my drink over.	我笨手笨脚地打翻了饮料。
bow	/baʊ/	v. 鞠躬	NCE2 Lesson 70	The actors bow at the end of the play.	演员们在演出结束时鞠躬。
safety	/ˈseɪfti/	n. 安全地带	NCE2 Lesson 70	We all got out of the building to safety.	我们都从楼里撤到了安全的地方。
sympathetically	/ˌsɪmpəˈθetɪkli/	adv. 同情地	NCE2 Lesson 70	She listened sympathetically as I explained the problem.	我说明问题时，她体谅地听着。
parliament	/ˈpɑːləmənt/	n. 议会，国会	NCE2 Lesson 71	The bill is being discussed in parliament.	议会正在讨论这项法案。
erect	/ɪˈrekt/	v. 建起	NCE2 Lesson 71	They plan to erect a fence around the garden.	他们计划在花园周围建一道栅栏。
accurate	/ˈækjərət/	adj. 准确的	NCE2 Lesson 71	Are these figures accurate?	这些数字准确吗？
official	/əˈfɪʃ(ə)l/	n. 官员，行政人员	NCE2 Lesson 71	An official checked our documents at the border.	一位官员在边境检查了我们的证件。
Greenwich	/ˈɡrenɪtʃ/	n. 格林尼治	NCE2 Lesson 71	Shall we visit Greenwich on Sunday?	我们星期天去格林尼治逛逛好吗？
observatory	/əbˈzɜːvətri/	n. 天文台	NCE2 Lesson 71	The observatory is open to visitors tonight.	天文台今晚对游客开放。
check	/tʃek/	v. 检查	NCE2 Lesson 71	Could you check the address for me?	你能帮我核对一下地址吗？
microphone	/ˈmaɪkrəfəʊn/	n. 扩音器，麦克风	NCE2 Lesson 71	Is this microphone working?	这个麦克风能用吗？
tower	/ˈtaʊə(r)/	n. 塔	NCE2 Lesson 71	You can climb the tower for a better view.	你可以爬上塔，看看更开阔的风景。
racing	/ˈreɪsɪŋ/	n. 竞赛	NCE2 Lesson 72	My brother is interested in motor racing.	我哥哥对赛车感兴趣。
per	/pə(r)/	prep. 每	NCE2 Lesson 72	The room costs eighty pounds per night.	这个房间每晚八十英镑。
Utah	/ˈjuːtɑː/	n. 犹他（美国州名）	NCE2 Lesson 72	My cousin lives in Utah.	我表哥住在犹他州。
horsepower	/ˈhɔːspaʊə(r)/	n. 马力	NCE2 Lesson 72	How much horsepower does that engine produce?	那台发动机有多少马力？
burst	/bɜːst/	v. 爆裂	NCE2 Lesson 72	The balloon could burst if you blow too hard.	你吹得太用力，气球可能会破。
average	/ˈævərɪdʒ/	adj. 平均的	NCE2 Lesson 72	What's the average rent around here?	这一带的平均租金是多少？
footstep	/ˈfʊtstep/	n. 脚步，脚步声；足迹	NCE2 Lesson 72	I heard a footstep outside my door.	我听到门外有一声脚步声。
record-holder	/ˈrekɔːd həʊldə(r)/	n. 纪录保持者	NCE2 Lesson 73	Is she still the world record-holder?	她仍是世界纪录保持者吗？
truant	/ˈtruːənt/	n. 逃学的孩子	NCE2 Lesson 73	The teacher spoke to the truant's parents.	老师和那个逃学孩子的父母谈了话。
hitchhike	/ˈhɪtʃhaɪk/	v. 搭便车旅行	NCE2 Lesson 73	We used to hitchhike when we were students.	我们还是学生时常常搭便车旅行。
meantime	/ˈmiːntaɪm/	n. 其间	NCE2 Lesson 73	Dinner will be ready soon. In the meantime, have a seat.	晚饭很快就好，在这之前先坐一会儿。
lorry	/ˈlɒri/	n. 卡车	NCE2 Lesson 73	A lorry is blocking the entrance.	一辆卡车挡住了入口。
border	/ˈbɔːdə(r)/	n. 边界	NCE2 Lesson 73	Do we need passports to cross the border?	我们过边境需要护照吗？
evade	/ɪˈveɪd/	v. 逃避，逃离	NCE2 Lesson 73	He tried to evade my question.	他试图回避我的问题。
unimaginative	/ˌʌnɪˈmædʒɪnətɪv/	adj. 缺乏想像力的	NCE2 Lesson 73	The menu is rather unimaginative.	这份菜单没什么新意。
shame	/ʃeɪm/	n. 惭愧，羞耻	NCE2 Lesson 73	There's no shame in asking for help.	寻求帮助没什么可羞耻的。
limelight	/ˈlaɪmlaɪt/	n. 公众注意的中心；舞台灯光	NCE2 Lesson 74	She doesn't enjoy being in the limelight.	她不喜欢成为公众关注的焦点。
precaution	/prɪˈkɔːʃ(ə)n/	n. 预防措施	NCE2 Lesson 74	I took a spare key as a precaution.	我带了把备用钥匙，以防万一。
fan	/fæn/	n. 狂热者，迷	NCE2 Lesson 74	I'm a big fan of her music.	我很喜欢她的音乐。
shady	/ˈʃeɪdi/	adj. 遮荫的	NCE2 Lesson 74	Let's find a shady spot for lunch.	我们找个阴凉的地方吃午饭吧。
sheriff	/ˈʃerɪf/	n. 司法长官	NCE2 Lesson 74	The sheriff appears at the end of the film.	治安官在电影结尾出现。
sneer	/snɪə(r)/	n. 冷笑	NCE2 Lesson 74	I didn't like the sneer on his face.	我不喜欢他脸上那副嘲讽的表情。
thick	/θɪk/	adj. 厚的	NCE2 Lesson 75	You'll need a thick coat today.	你今天得穿件厚外套。
signal	/ˈsɪɡnəl/	n. 信号	NCE2 Lesson 75	There's no phone signal here.	这里没有手机信号。
stamp	/stæmp/	v. 跺，踩	NCE2 Lesson 75	Don't stamp your feet on the stairs.	别在楼梯上跺脚。
helicopter	/ˈhelɪkɒptə(r)/	n. 直升飞机	NCE2 Lesson 75	We heard a helicopter overhead.	我们听到头顶有直升机的声音。
scene	/siːn/	n. 现场	NCE2 Lesson 75	The police arrived at the scene quickly.	警方很快就到达了现场。
survivor	/səˈvaɪvə(r)/	n. 幸存者	NCE2 Lesson 75	We heard an interview with a survivor of the fire.	我们听了对那场火灾的一位幸存者的采访。
fool	/fuːl/	n. 傻瓜	NCE2 Lesson 76	I felt like a fool for forgetting her name.	我忘了她的名字，觉得自己像个傻瓜。
bulletin	/ˈbʊlətɪn/	n. 新闻简报	NCE2 Lesson 76	Did you hear the latest news bulletin?	你听最新的新闻简报了吗？
announcer	/əˈnaʊnsə(r)/	n. （电视、电台）播音员	NCE2 Lesson 76	The announcer said the programme would start late.	播音员说节目会推迟开始。
macaroni	/ˌmækəˈrəʊni/	n. 通心面，空心面条	NCE2 Lesson 76	Shall I make macaroni cheese for dinner?	晚饭我做芝士通心粉好吗？
leading	/ˈliːdɪŋ/	adj. 主要的	NCE2 Lesson 76	She's a leading expert in the field.	她是这个领域的顶尖专家。
grower	/ˈɡrəʊə(r)/	n. 种植者	NCE2 Lesson 76	We buy our apples from a local grower.	我们从当地果农那里买苹果。
splendid	/ˈsplendɪd/	adj. 极好的	NCE2 Lesson 76	What a splendid view!	多么壮丽的景色！
stalk	/stɔːk/	n. 梗	NCE2 Lesson 76	Cut the stalk off before you cook it.	烹饪前先把梗切掉。
thresh	/θreʃ/	v. 打（庄稼）	NCE2 Lesson 76	They use a machine to thresh the wheat.	他们用机器给小麦脱粒。
process	/ˈprəʊses/	v. 加工	NCE2 Lesson 76	This factory can process fruit into juice.	这家工厂能把水果加工成果汁。
Signor	/ˈsiːnjɔː(r)/	n. （意大利语）先生	NCE2 Lesson 76	Good morning, Signor Rossi.	早上好，罗西先生。
champion	/ˈtʃæmpiən/	n. 冠军	NCE2 Lesson 76	She's the national swimming champion.	她是全国游泳冠军。
studio	/ˈstjuːdiəʊ/	n. 录音室，播音室；工作室	NCE2 Lesson 76	The band is recording in the studio today.	乐队今天在录音室录音。
mummy	/ˈmʌmi/	n. 木乃伊	NCE2 Lesson 77	We saw a mummy in the museum.	我们在博物馆看到了一具木乃伊。
Egyptian	/iˈdʒɪpʃn/	adj. 埃及的	NCE2 Lesson 77	Have you seen the Egyptian exhibition?	你看过那个埃及展览吗？
temple	/ˈtemp(ə)l/	n. 庙	NCE2 Lesson 77	Please take your shoes off before entering the temple.	进寺庙前请脱鞋。
mark	/mɑːk/	n. 斑点	NCE2 Lesson 77	There's a coffee mark on your shirt.	你的衬衫上有一块咖啡渍。
plate	/pleɪt/	n. （照相）底片	NCE2 Lesson 77	This old camera uses a glass plate.	这台老相机使用玻璃底片。
disease	/dɪˈziːz/	n. 疾病	NCE2 Lesson 77	The disease damaged many trees in the park.	这种病害损坏了公园里的许多树。
last	/lɑːst/	v. 持续	NCE2 Lesson 77	How long does the course last?	这门课程持续多久？
prove	/pruːv/	v. 显示出	NCE2 Lesson 77	This map may prove useful later.	这张地图稍后可能会派上用场。
resin	/ˈrezɪn/	n. 树脂	NCE2 Lesson 77	There's sticky resin on the tree bark.	树皮上有黏黏的树脂。
skin	/skɪn/	n. 皮肤	NCE2 Lesson 77	This soap makes my skin feel dry.	这种肥皂让我觉得皮肤干燥。
section	/ˈsekʃ(ə)n/	n. 切片	NCE2 Lesson 77	We examined a thin section of the leaf.	我们观察了叶片的一个薄切片。
figure	/ˈfɪɡə(r)/	n. （人的）体形；人像	NCE2 Lesson 77	There's a wooden figure on the shelf.	架子上有一尊木制人像。
normally	/ˈnɔːməli/	adv. 通常地	NCE2 Lesson 77	I normally leave home at eight.	我通常八点出门。
survive	/səˈvaɪv/	v. 幸免于	NCE2 Lesson 77	Could these plants survive a cold winter?	这些植物能熬过寒冬吗？
entitle	/ɪnˈtaɪt(ə)l/	v. 以……为名	NCE2 Lesson 78	Why did you entitle your story "Home"?	你为什么把故事取名为《家》？
calm	/kɑːm/	v. 使镇定	NCE2 Lesson 78	Take a moment to calm yourself.	花点时间让自己冷静下来。
nerve	/nɜːv/	n. 神经	NCE2 Lesson 78	The dentist said a nerve was damaged.	牙医说一根神经受损了。
concentration	/ˌkɒnsənˈtreɪʃən/	n. 集中，专心	NCE2 Lesson 78	That noise is breaking my concentration.	那噪声让我无法集中注意力。
suffer	/ˈsʌfə(r)/	v. 受苦，受害	NCE2 Lesson 78	Do you suffer from travel sickness?	你晕车吗？
symptom	/ˈsɪmptəm/	n. 症状	NCE2 Lesson 78	Was a cough your first symptom?	咳嗽是你最早的症状吗？
temper	/ˈtempə(r)/	n. 脾气	NCE2 Lesson 78	I shouldn't have lost my temper.	我不该发脾气。
appetite	/ˈæpɪtaɪt/	n. 胃口，食欲	NCE2 Lesson 78	I haven't got much of an appetite today.	我今天没什么胃口。
produce	/prəˈdjuːs/	v. 拿出	NCE2 Lesson 78	Could you produce some proof of your address?	你能出示一些住址证明吗？
urge	/ɜːdʒ/	v. 力劝，怂恿	NCE2 Lesson 78	I urge you to think about it carefully.	我强烈建议你仔细考虑一下。
satisfaction	/ˌsætɪsˈfækʃ(ə)n/	n. 满意，满足	NCE2 Lesson 78	Finishing the job gave me real satisfaction.	完成这项工作让我很有满足感。
delighted	/dɪˈlaɪtɪd/	adj. 欣喜的	NCE2 Lesson 78	I'd be delighted to come.	我很乐意来。
parent	/ˈpeərənt/	n. 父（母）亲	NCE2 Lesson 79	A parent needs to sign this form.	这张表需要一位家长签字。
flight attendant	/ˈflaɪt əˈtendənt/	n. 空中乘务员	NCE2 Lesson 79	Let's ask the flight attendant for some water.	我们向乘务员要点水吧。
frightened	/ˈfraɪt(ə)nd/	adj. 害怕，担惊	NCE2 Lesson 79	I was frightened by the sudden noise.	突然的声响吓到了我。
curious	/ˈkjʊəriəs/	adj. 急于了解，好奇的	NCE2 Lesson 79	I'm curious about how you met.	我很好奇你们是怎么认识的。
bomb	/bɒm/	n. 炸弹	NCE2 Lesson 79	The film starts with a bomb scare.	电影以一次炸弹恐慌事件开场。
palace	/ˈpæləs/	n. 宫殿	NCE2 Lesson 80	Can we visit the palace gardens?	我们能参观宫殿花园吗？
extraordinary	/ɪkˈstrɔːd(ə)n(ə)ri/	adj. 不平常的，非凡的	NCE2 Lesson 80	She has an extraordinary memory for names.	她记名字的能力非同寻常。
exhibition	/ˌeksɪˈbɪʃ(ə)n/	n. 展览	NCE2 Lesson 80	There's a photography exhibition at the library.	图书馆里有一个摄影展。
iron	/ˈaɪən/	n. 铁	NCE2 Lesson 80	Is this gate made of iron?	这扇门是铁做的吗？
various	/ˈveəriəs/	adj. 各种各样的	NCE2 Lesson 80	I've tried various ways to fix it.	我试过各种方法来修好它。
machinery	/məˈʃiːnəri/	n. 机器	NCE2 Lesson 80	Please keep clear of the machinery.	请与这些机器保持距离。
display	/dɪˈspleɪ/	n. 展览	NCE2 Lesson 80	There's a display of old photographs upstairs.	楼上有一个老照片展。
steam	/stiːm/	n. 蒸汽	NCE2 Lesson 80	Be careful of the steam from the kettle.	小心水壶冒出的蒸汽。
profit	/ˈprɒfɪt/	n. 利润	NCE2 Lesson 80	Did the shop make a profit last year?	那家店去年盈利了吗？
        """.trimIndent(),
        """
college	/ˈkɒlɪdʒ/	n. 学院	NCE2 Lesson 80	What did you study at college?	你在学院学的是什么？
prisoner	/ˈprɪz(ə)nə(r)/	n. 囚犯	NCE2 Lesson 81	The film is about an escaped prisoner.	这部电影讲的是一个越狱囚犯的故事。
bush	/bʊʃ/	n. 灌木丛	NCE2 Lesson 81	The ball landed behind that bush.	球落在了那丛灌木后面。
rapidly	/ˈræpɪdli/	adv. 迅速地	NCE2 Lesson 81	The weather is changing rapidly.	天气正在迅速变化。
uniform	/ˈjuːnɪfɔːm/	n. 制服	NCE2 Lesson 81	Do you have to wear a uniform at work?	你上班必须穿制服吗？
rifle	/ˈraɪf(ə)l/	n. 来福枪，步枪	NCE2 Lesson 81	There's an old rifle on display in the museum.	博物馆里陈列着一支旧步枪。
shoulder	/ˈʃəʊldə(r)/	n. 肩	NCE2 Lesson 81	My shoulder hurts when I lift my arm.	我抬胳膊时肩膀疼。
march	/mɑːtʃ/	v. 行进	NCE2 Lesson 81	We watched the band march down the street.	我们看着乐队沿街行进。
boldly	/ˈbəʊldli/	adv. 大胆地	NCE2 Lesson 81	She walked boldly onto the stage.	她大胆地走上了舞台。
blaze	/bleɪz/	v. 闪耀	NCE2 Lesson 81	The lights blaze all night in that building.	那栋楼里的灯整夜通明。
salute	/səˈluːt/	v. 行礼	NCE2 Lesson 81	The soldiers salute as the flag goes up.	旗帜升起时，士兵们敬礼。
elderly	/ˈeldəli/	adj. 上了年纪的	NCE2 Lesson 81	I help my elderly neighbour with her shopping.	我帮年迈的邻居买东西。
grey	/ɡreɪ/	adj. 灰白的	NCE2 Lesson 81	He's started to go grey.	他的头发开始变灰白了。
sharp	/ʃɑːp/	adj. 猛烈的	NCE2 Lesson 81	I felt a sharp pain in my knee.	我的膝盖突然一阵剧痛。
blow	/bləʊ/	n. 打击	NCE2 Lesson 81	Losing the contract was a real blow.	失去那份合同是个沉重的打击。
monster	/ˈmɒnstə(r)/	n. 怪物	NCE2 Lesson 82	The child thought there was a monster under the bed.	那孩子以为床底下有个怪物。
sailor	/ˈseɪlə(r)/	n. 海员	NCE2 Lesson 82	My uncle used to be a sailor.	我叔叔以前是一名海员。
creature	/ˈkriːtʃə(r)/	n. 动物，生物	NCE2 Lesson 82	What's that little creature in the pond?	池塘里那个小生物是什么？
peculiar	/pɪˈkjuːliə(r)/	adj. 奇怪，不寻常的	NCE2 Lesson 82	There's a peculiar smell in here.	这里有一股奇怪的气味。
shining	/ˈʃaɪnɪŋ/	adj. 闪闪发光的	NCE2 Lesson 82	You could see her shining eyes in the photo.	从照片上可以看到她明亮的眼睛。
oarfish	/ˈɔːfɪʃ/	n. 皇带鱼，桨鱼	NCE2 Lesson 82	Have you ever seen an oarfish?	你见过皇带鱼吗？
election	/ɪˈlekʃ(ə)n/	n. 选举	NCE2 Lesson 83	When is the next election?	下一次选举是什么时候？
former	/ˈfɔːmə(r)/	adj. 以前的，从前的	NCE2 Lesson 83	I ran into a former colleague yesterday.	我昨天偶遇了一位以前的同事。
defeat	/dɪˈfiːt/	v. 打败	NCE2 Lesson 83	Do you think we can defeat them?	你觉得我们能打败他们吗？
fanatical	/fəˈnætɪkl/	adj. 狂热的	NCE2 Lesson 83	He's fanatical about football.	他对足球十分狂热。
opponent	/əˈpəʊnənt/	n. 反对者，对手	NCE2 Lesson 83	Her opponent played really well.	她的对手打得非常好。
radical	/ˈrædɪk(ə)l/	adj. 彻底的，根本的；激进的	NCE2 Lesson 83	That would be a radical change.	那将是一个彻底的改变。
progressive	/prəˈɡresɪv/	adj. 进步的	NCE2 Lesson 83	The school has a progressive approach to teaching.	这所学校采用进步的教学理念。
prefix	/ˈpriːfɪks/	n. 前缀	NCE2 Lesson 83	What does the prefix "un-" mean?	前缀“un-”是什么意思？
suspicious	/səˈspɪʃəs/	adj. 怀疑的	NCE2 Lesson 83	I'm suspicious of emails asking for bank details.	我对索要银行信息的邮件持怀疑态度。
strike	/straɪk/	n. 罢工	NCE2 Lesson 84	The drivers are on strike today.	司机们今天在罢工。
busman	/ˈbʌsmən/	n. 公共汽车司机	NCE2 Lesson 84	My grandad worked as a busman for years.	我爷爷在公交行业干了很多年。
state	/steɪt/	v. 正式提出，宣布	NCE2 Lesson 84	Please state your full name.	请说出你的全名。
agreement	/əˈɡriːmənt/	n. 协议	NCE2 Lesson 84	Have we reached an agreement?	我们达成协议了吗？
relieve	/rɪˈliːv/	v. 减轻	NCE2 Lesson 84	A short walk helps relieve my stress.	短暂散步有助于缓解我的压力。
pressure	/ˈpreʃə(r)/	n. 压力，麻烦	NCE2 Lesson 84	I'm under a lot of pressure at work.	我的工作压力很大。
extent	/ɪkˈstent/	n. 程度	NCE2 Lesson 84	I agree with you to some extent.	我在某种程度上同意你的看法。
volunteer	/ˌvɒlənˈtɪə(r)/	v. 自动提出，自愿	NCE2 Lesson 84	Would you like to volunteer at the weekend?	你周末想做志愿者吗？
gratitude	/ˈɡrætɪtjuːd/	n. 感激	NCE2 Lesson 84	I sent her a card to express my gratitude.	我送了她一张卡片，表达我的感激之情。
object	/əbˈdʒekt/	v. 不赞成，反对	NCE2 Lesson 84	Would anyone object if I opened the window?	如果我开窗，有人反对吗？
inform	/ɪnˈfɔːm/	v. 告诉，通知	NCE2 Lesson 85	Please inform us of any changes.	如有任何变更，请通知我们。
headmaster	/ˌhedˈmɑːstə(r)/	n. 校长	NCE2 Lesson 85	The headmaster spoke to us after assembly.	集会后，校长跟我们讲了话。
contribute	/kənˈtrɪbjuːt/	v. 捐助，援助	NCE2 Lesson 85	Would you like to contribute to the leaving present?	你想为离别礼物出一份钱吗？
gift	/ɡɪft/	n. 礼物，赠品	NCE2 Lesson 85	Thank you for the lovely gift.	谢谢你送我这么好的礼物。
album	/ˈælbəm/	n. 签名簿，相册	NCE2 Lesson 85	Let's look through the photo album.	我们翻翻相册吧。
patience	/ˈpeɪʃ(ə)ns/	n. 耐心	NCE2 Lesson 85	Thanks for your patience.	谢谢你的耐心。
encouragement	/ɪnˈkʌrɪdʒmənt/	n. 鼓励	NCE2 Lesson 85	Your encouragement really helped me.	你的鼓励真的帮助了我。
farewell	/ˌfeəˈwel/	n. 告别	NCE2 Lesson 85	We're having a farewell dinner for Tom.	我们要为汤姆办一场告别晚宴。
honour	/ˈɒnə(r)/	n. 敬意	NCE2 Lesson 85	The dinner is in her honour.	这场晚宴是为向她表示敬意而举办的。
coincidence	/kəʊˈɪnsɪdəns/	n. 巧合	NCE2 Lesson 85	What a coincidence! We went to the same school.	真巧！我们上过同一所学校。
total	/ˈtəʊt(ə)l/	n. 总数	NCE2 Lesson 85	What's the total, including delivery?	包括运费一共多少钱？
devote	/dɪˈvəʊt/	v. 致力于	NCE2 Lesson 85	I'd like to devote more time to reading.	我想花更多时间阅读。
gardening	/ˈɡɑːdnɪŋ/	n. 园艺	NCE2 Lesson 85	Do you enjoy gardening?	你喜欢园艺吗？
hobby	/ˈhɒbi/	n. 爱好，嗜好	NCE2 Lesson 85	Photography is my main hobby.	摄影是我主要的爱好。
swing	/swɪŋ/	v. 转向	NCE2 Lesson 86	The road will swing to the left ahead.	前面的路会向左拐。
speedboat	/ˈspiːdbəʊt/	n. 快艇	NCE2 Lesson 86	We took a speedboat to the island.	我们坐快艇去了那座岛。
desperately	/ˈdespərətli/	adv. 绝望地	NCE2 Lesson 86	I searched desperately for my missing passport.	我心急如焚地寻找丢失的护照。
companion	/kəmˈpænjən/	n. 同伙，伙伴	NCE2 Lesson 86	She was a great travelling companion.	她是个很好的旅伴。
water ski	/ˈwɔːtə(r) skiː/	v. 滑水（也写作 water-ski）；n. 滑水板	NCE2 Lesson 86	Have you ever tried to water ski?	你试过滑水吗？
buoy	/bɔɪ/	n. 浮标	NCE2 Lesson 86	Don't swim beyond that buoy.	不要游过那个浮标。
tremendous	/trəˈmendəs/	adj. 巨大的	NCE2 Lesson 86	You've made tremendous progress.	你取得了巨大的进步。
petrol	/ˈpetrəl/	n. 汽油	NCE2 Lesson 86	We need to stop for petrol.	我们需要停车加油。
drift	/drɪft/	v. 漂动，漂流；v. 漂流	NCE2 Lesson 86, NCE2 Lesson 96	Watch the leaves drift down the stream.	看那些叶子顺着小溪漂走。
gently	/ˈdʒentli/	adv. 缓慢地，轻轻地	NCE2 Lesson 86	Close the door gently, please.	请轻轻关门。
alibi	/ˈæləbaɪ/	n. 不在场证明	NCE2 Lesson 87	The suspect had an alibi for that evening.	嫌疑人有那天晚上的不在场证明。
commit	/kəˈmɪt/	v. 犯（罪、错）	NCE2 Lesson 87	Did he actually commit a crime?	他真的犯了罪吗？
inspector	/ɪnˈspektə(r)/	n. 探长	NCE2 Lesson 87	The inspector wants to speak to you.	探长想和你谈谈。
employer	/ɪmˈplɔɪə(r)/	n. 雇主	NCE2 Lesson 87	Does your employer pay for training?	你的雇主支付培训费用吗？
confirm	/kənˈfɜːm/	v. 确认，证实	NCE2 Lesson 87	Could you confirm the booking by email?	你能通过邮件确认预约吗？
truth	/truːθ/	n. 真相	NCE2 Lesson 87	Please tell me the truth.	请告诉我真相。
trap	/træp/	v. 陷入，使陷于困境	NCE2 Lesson 88	Floodwater can trap people in their homes.	洪水可能会把人困在家里。
surface	/ˈsɜːfɪs/	n. 地面，表面	NCE2 Lesson 88	Let the surface dry before painting.	等表面干了再刷漆。
explosive	/ɪkˈspləʊsɪv/	n. 炸药	NCE2 Lesson 88	The crew used an explosive to break up the rock.	施工人员用炸药炸开了岩石。
vibration	/vaɪˈbreɪʃ(ə)n/	n. 震动	NCE2 Lesson 88	I can feel a vibration through the floor.	我能感觉到地板传来的震动。
collapse	/kəˈlæps/	v. 坍塌	NCE2 Lesson 88	The old wall could collapse at any time.	那堵旧墙随时可能倒塌。
drill	/drɪl/	v. 钻孔	NCE2 Lesson 88	We need to drill a hole for the shelf.	我们需要为这个架子钻个孔。
capsule	/ˈkæpsjuːl/	n. 舱，密封容器；胶囊	NCE2 Lesson 88	The museum displays a space capsule.	博物馆里陈列着一个太空舱。
layer	/ˈleɪə(r)/	n. 层	NCE2 Lesson 88	Put on another layer if you're cold.	冷的话就再加一层衣服。
beneath	/bɪˈniːθ/	prep. 在......之下	NCE2 Lesson 88	There's a cupboard beneath the stairs.	楼梯下面有一个橱柜。
lower	/ˈləʊə(r)/	v. 放下，降低	NCE2 Lesson 88	Could you lower your voice a little?	你说话声音能小一点吗？
progress	/prəˈɡres/	v. 进展，进行	NCE2 Lesson 88	I hope to progress to the next level soon.	我希望很快能进阶到下一个级别。
smoothly	/ˈsmuːðli/	adv. 顺利地	NCE2 Lesson 88	Everything went smoothly today.	今天一切都很顺利。
slip	/slɪp/	n. 小错误	NCE2 Lesson 89	Sorry, that was a slip of the tongue.	对不起，那是口误。
comedy	/ˈkɒmədi/	n. 喜剧	NCE2 Lesson 89	Shall we watch a comedy tonight?	我们今晚看一部喜剧好吗？
queue	/kjuː/	v. 排队	NCE2 Lesson 89	Do we need to queue for tickets?	我们需要排队买票吗？
dull	/dʌl/	adj. 枯燥，无味	NCE2 Lesson 89	The first half of the film was dull.	电影的前半部分很无聊。
artiste	/ɑːˈtiːst/	n. 艺人	NCE2 Lesson 89	The cabaret artiste came back for an encore.	那位歌舞艺人返场加演了一段。
advertiser	/ˈædvətaɪzə(r)/	n. 广告客户，登广告者	NCE2 Lesson 89	Who's the main advertiser on this website?	这个网站的主要广告客户是谁？
chip	/tʃɪp/	n. 油煎土豆片	NCE2 Lesson 90	Can I try a chip from your plate?	我能尝一根你盘子里的薯条吗？
overfish	/ˌəʊvəˈfɪʃ/	v. 过度捕捞	NCE2 Lesson 90	If we overfish this area, stocks won't recover.	如果我们在这个区域过度捕捞，鱼群数量就无法恢复。
giant	/ˈdʒaɪənt/	adj. 巨大的	NCE2 Lesson 90	There's a giant tree in the garden.	花园里有一棵大树。
terrify	/ˈterɪfaɪ/	v. 吓，使恐怖	NCE2 Lesson 90	Spiders terrify me.	我很害怕蜘蛛。
diver	/ˈdaɪvə(r)/	n. 潜水员	NCE2 Lesson 90	The diver found an old coin underwater.	那位潜水员在水下找到了一枚旧硬币。
oil rig	/ˈɔɪl rɪɡ/	n. 石油钻塔	NCE2 Lesson 90	My cousin works on an oil rig.	我表哥在石油钻井平台上工作。
wit	/wɪt/	n. 机智，幽默；wits 指理智，头脑	NCE2 Lesson 90	Her quick wit always makes us laugh.	她机敏风趣，总能把我们逗笑。
cage	/keɪdʒ/	n. 笼	NCE2 Lesson 90	The bird flew out of its cage.	鸟从笼子里飞了出来。
shark	/ʃɑːk/	n. 鲨鱼	NCE2 Lesson 90	Have you ever seen a shark up close?	你近距离见过鲨鱼吗？
whale	/weɪl/	n. 鲸	NCE2 Lesson 90	We saw a whale from the boat.	我们从船上看到了一头鲸。
variety	/vəˈraɪəti/	n. 品种	NCE2 Lesson 90	Which variety of apple do you prefer?	你更喜欢哪种苹果？
cod	/kɒd/	n. 鳕	NCE2 Lesson 90	I'll have the cod and chips, please.	请给我鳕鱼配薯条。
        """.trimIndent(),
        """
skate	/skeɪt/	n. 鳐	NCE2 Lesson 90	I've never tried skate before.	我以前从没吃过鳐鱼。
factor	/ˈfæktə(r)/	n. 因素	NCE2 Lesson 90	Price isn't the only factor in our decision.	价格不是我们作决定的唯一因素。
crew	/kruː/	n. 全体工作人员	NCE2 Lesson 90	The crew were very helpful during the flight.	机组人员在飞行途中帮了很多忙。
special	/ˈspeʃ(ə)l/	adj. 特别的	NCE2 Lesson 90	Is there anything special you'd like for dinner?	晚饭你有没有什么特别想吃的？
balloon	/bəˈluːn/	n. 气球	NCE2 Lesson 91	Hold tight to your balloon.	抓紧你的气球。
royal	/ˈrɔɪəl/	adj. 皇家	NCE2 Lesson 91	We visited the royal gardens.	我们参观了皇家花园。
spy	/spaɪ/	v. 侦察	NCE2 Lesson 91	Don't spy on your neighbours.	不要窥探你的邻居。
track	/træk/	n. 轨迹，踪迹	NCE2 Lesson 91	I found a fresh animal track in the mud.	我在泥里发现了一个新鲜的动物足迹。
binoculars	/bɪˈnɒkjələz/	n. 望远镱	NCE2 Lesson 91	Bring your binoculars if you want to watch birds.	如果你想观鸟，就带上双筒望远镜。
fast	/fɑːst/	adv. 熟（睡）	NCE2 Lesson 92	The baby is fast asleep.	宝宝睡得正熟。
ladder	/ˈlædə(r)/	n. 梯子	NCE2 Lesson 92	Could you hold the ladder steady?	你能把梯子扶稳吗？
shed	/ʃed/	n. 棚子	NCE2 Lesson 92	The garden tools are in the shed.	园艺工具放在棚子里。
sarcastic	/sɑːˈkæstɪk/	adj. 讽刺的，讥笑的	NCE2 Lesson 92	Are you being sarcastic?	你是在说反话吗？
tone	/təʊn/	n. 语气，腔调	NCE2 Lesson 92	I didn't like his tone of voice.	我不喜欢他说话的语气。
noble	/ˈnəʊb(ə)l/	adj. 高尚的，壮丽的	NCE2 Lesson 93	Helping others is a noble aim.	帮助别人是一个高尚的目标。
monument	/ˈmɒnjumənt/	n. 纪念碑	NCE2 Lesson 93	Let's meet by the monument.	我们在纪念碑旁边见吧。
statue	/ˈstætʃuː/	n. 雕像	NCE2 Lesson 93	Who's that statue of?	那是谁的雕像？
liberty	/ˈlɪbəti/	n. 自由	NCE2 Lesson 93	The statue is a symbol of liberty.	这座雕像是自由的象征。
sculptor	/ˈskʌlptə(r)/	n. 雕刻家	NCE2 Lesson 93	Do you know who the sculptor was?	你知道雕塑家是谁吗？
actual	/ˈæktʃuəl/	adj. 实际的，真实的	NCE2 Lesson 93	What's the actual cost after tax?	税后的实际费用是多少？
copper	/ˈkɒpə(r)/	n. 铜	NCE2 Lesson 93	These pipes are made of copper.	这些管道是铜做的。
support	/səˈpɔːt/	v. 支持，支撑	NCE2 Lesson 93	This beam helps support the roof.	这根梁帮助支撑屋顶。
framework	/ˈfreɪmwɜːk/	n. 构架，框架	NCE2 Lesson 93	The wooden framework is still in good condition.	木制框架仍然状况良好。
transport	/trænˈspɔːt/	v. 运送	NCE2 Lesson 93	How will we transport the furniture?	我们要怎么运这些家具？
site	/saɪt/	n. 场地	NCE2 Lesson 93	Visitors must sign in at the building site.	访客必须在工地登记。
pedestal	/ˈpedɪst(ə)l/	n. 底座	NCE2 Lesson 93	The statue stands on a stone pedestal.	雕像立在一个石头底座上。
Los Angeles	/lɔ:s ˈeɪndʒəlz/	n. 洛杉矶	NCE2 Lesson 94	How long is the flight to Los Angeles?	飞往洛杉矶的航班要多久？
reluctant	/rɪˈlʌktənt/	adj. 勉强的，不愿意的	NCE2 Lesson 94	I'm reluctant to sign before reading it.	没看过内容之前，我不愿意签字。
weight	/weɪt/	n. 重物	NCE2 Lesson 94	I can't lift that weight on my own.	我一个人抬不动那么重的东西。
underwater	/ˌʌndəˈwɔːtə(r)/	adj. 水下的	NCE2 Lesson 94	Is this an underwater camera?	这是一台水下相机吗？
tricycle	/ˈtraɪsɪk(ə)l/	n. 三轮车	NCE2 Lesson 94	My little nephew rides a tricycle.	我的小侄子骑三轮车。
compete	/kəmˈpiːt/	v. 比赛，对抗	NCE2 Lesson 94	Are you going to compete in the race?	你要参加那场比赛吗？
yard	/jɑːd/	n. 码	NCE2 Lesson 94	Move the bench about a yard to the left.	把长椅往左移大约一码。
gasp	/ɡɑːsp/	v. 喘气	NCE2 Lesson 94	The cold water made me gasp.	冷水让我猛地吸了口气。
fantasy	/ˈfæntəsi/	n. 幻想故事	NCE2 Lesson 95	I enjoy reading fantasy novels.	我喜欢读奇幻小说。
ambassador	/æmˈbæsədə(r)/	n. 大使	NCE2 Lesson 95	The ambassador gave a short speech.	大使作了一段简短的讲话。
Escalopia		n. 艾斯卡罗比亚（虚构国名，音标待核对）	NCE2 Lesson 95	Escalopia is an imaginary country in the story.	艾斯卡罗比亚是故事中的虚构国家。
frightful	/ˈfraɪtf(ə)l/	adj. 可怕的，令人吃惊的	NCE2 Lesson 95	What a frightful mess!	怎么乱成这样！
fire extinguisher	/ˈfaɪər ɪkˈstɪŋɡwɪʃə(r)/	n. 灭火器	NCE2 Lesson 95	Where's the nearest fire extinguisher?	最近的灭火器在哪里？
drily	/ˈdraɪli/	adv. 冷淡地，枯燥无味地	NCE2 Lesson 95	She said drily, "What a surprise."	她冷冷地说：“真是意外啊。”
embassy	/ˈembəsi/	n. 大使馆	NCE2 Lesson 95	I need to contact the embassy.	我需要联系大使馆。
heaven	/ˈhev(ə)n/	n. 天，天堂	NCE2 Lesson 95	This quiet beach feels like heaven.	这片安静的海滩让人觉得像天堂一样。
basement	/ˈbeɪsmənt/	n. 地下室	NCE2 Lesson 95	The washing machine is in the basement.	洗衣机在地下室。
definitely	/ˈdefɪnətli/	adv. 肯定地	NCE2 Lesson 95	I'll definitely be there.	我一定会到的。
post	/pəʊst/	v. 派任	NCE2 Lesson 95	Will they post you abroad next year?	他们明年会把你派到国外吗？
shot	/ʃɒt/	n. 射击，枪声；弹丸	NCE2 Lesson 95	We heard a shot in the distance.	我们听到远处传来一声枪响。
aim	/eɪm/	n. 瞄准	NCE2 Lesson 95	The player took aim at the goal.	那名球员瞄准了球门。
festival	/ˈfestɪvl/	n. 节日	NCE2 Lesson 96	Are you going to the music festival?	你要去参加音乐节吗？
lantern	/ˈlæntən/	n. 灯笼	NCE2 Lesson 96	We hung a lantern outside the tent.	我们在帐篷外挂了一盏灯。
spectacle	/ˈspektək(ə)l/	n. 景象，壮观，场面	NCE2 Lesson 96	The fireworks were quite a spectacle.	烟花的场面相当壮观。
guide	/ɡaɪd/	v. 带领	NCE2 Lesson 96	Can someone guide us back to the entrance?	有人能带我们回入口吗？
        """.trimIndent()
    )
}
